objects/REVVY__MnStrategy1__c.object
<CustomObject>
    <fields>
        <fullName>ApplicableProductsLong__c</fullName>
        <label>Applicable Products</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>Please enter the unique External ID. Only Alpha-numberical characters are allowed. Ex. You can copy the name of the pricing program and remove all spaces and special characters.</inlineHelpText>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Parent Pricing Program</description>
        <label>Parent Program</label>
        <referenceTo>REVVY__MnStrategy1__c</referenceTo>
        <relationshipLabel>Toro Pricing Programs</relationshipLabel>
        <relationshipName>Toro_Pricing_Programs</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/REVVY__MnStrategy4__c.object
<CustomObject>
    <fields>
        <fullName>Pricing_Program__c</fullName>
        <description>Store value of &quot;Pricing Program&quot; selected by user from &quot;Choose Pricing Program&quot; page. This value is applied to all quote items in this quote.</description>
        <label>Pricing Program</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Id__c</fullName>
        <formula>QuoteItem__r.REVVY__Catalog_Node__r.REVVY__Id__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>MODEL</label>
        <type>Text</type>
    </fields>
</CustomObject>

classes/ToroSouthernDemoSecondaryPricingProgram.cls
public class ToroSouthernDemoSecondaryPricingProgram extends ToroSecondaryPricingProgram {
	private Set<String> pricingProgramSet = new Set<String>();
	public Map<String, String> loadModelIdChartABPricingProgramMap(String pricingProgram) {
		system.debug(logginglevel.info, 'getAllowSupportPlus pricingProgram=' + pricingProgram);
		
		Map<String, String> modelIdPricingProgramMap = new Map<String, String>();
		ToroPricingProgramData ppd = new ToroPricingProgramData(pricingProgram);
		pricingProgramSet.add(ppd.externalId);
		system.debug(logginglevel.info, 'getAllowSupportPlus pricingProgram=' + ppd.externalId);
		List<Revvy__MnStrategy1__c> childrenPricingProgram = [Select Id, ExternalID__c, ApplicableProductsLong__c from Revvy__MnStrategy1__c where Parent_program__r.externalID__c = :ppd.externalId];
		for(Revvy__MnStrategy1__c pp : childrenPricingProgram) {
			pricingProgramSet.add(pp.ExternalID__c);
			if(String.isNotBlank(pp.ApplicableProductsLong__c)) {
				String[] parts = pp.ApplicableProductsLong__c.split(',');
				for(String p : parts) {
					modelIdPricingProgramMap.put(p, pp.ExternalID__c);	
				}
			}
		}
		system.debug('primary pp =' + ppd.externalId);
		Revvy__MnStrategy1__c southernDemo = ToroCacheManager.getPricingProgram(ppd.externalId);
		if(String.isNotBlank(southernDemo.ApplicableProductsLong__c)) {
			system.debug('primary ApplicableProductsLong__c =' + southernDemo.ApplicableProductsLong__c);
			String[] parts = southernDemo.ApplicableProductsLong__c.split(',');
			for(String p : parts) {
				modelIdPricingProgramMap.put(p, southernDemo.ExternalID__c);	
			}
		}
		return modelIdPricingProgramMap;	
	}
	
	public override decimal retrieveRebatePercentBasedOnBlendedDNet(Revvy__MnStrategy4__c qi, decimal dnetPercent, String ppExtId, String primaryExtId) {
		if(dnetPercent == null) {
			return 0;	
		}
		Map<String, String> model2pp = loadModelIdChartABPricingProgramMap(ppExtId);
		if(model2pp.containsKey(qi.Product_Id__c)) {
			system.debug('ToroSouthernDemoSecondaryPricingProgram 1');
			//qi.Pricing_Program__c=model2pp.get(qi.Product_Id__c);
			return retrieveRebatePercent(dnetPercent, model2pp.get(qi.Product_Id__c));		
		} else {
			system.debug('ToroSouthernDemoSecondaryPricingProgram 3');
			return 0;
		}
		
	}    
}