objects/REVVY__MnQuote__c.object
<CustomObject>
</CustomObject>

objects/Toro_PricingProgram__c.object
<CustomObject>
    <fields>
        <fullName>AllowSupportPlus__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Allow Support Plus</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ApplicableProducts__c</fullName>
        <label>Applicable Products</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Corporate_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Corporate Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Toro Pricing Programs</relationshipLabel>
        <relationshipName>Toro_Pricing_Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Exclude__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Exclude From Display</description>
        <inlineHelpText>Exclude From Display</inlineHelpText>
        <label>Exclude</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsFirstTee__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is this a first tee pricing program?  This flag is used in pricing program eligibility logic.</description>
        <label>Is First Tee</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsTaxSupported__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is this a tax supported pricing program? This flag is used in pricing program eligibility logic.</description>
        <label>Is Tax Supported</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MinimumTractionUnits__c</fullName>
        <description>Used by Small Package Restriction:
Package must be &gt;$50,000 at DN AND a minimum of 2 traction units.</description>
        <label>Minimum Traction Units</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OverriddenPriceList__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Overridden Price List</label>
        <referenceTo>REVVY__MnPriceList__c</referenceTo>
        <relationshipLabel>Toro Pricing Programs</relationshipLabel>
        <relationshipName>Toro_Pricing_Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PricingProgramStyle__c</fullName>
        <label>Pricing Program Style</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>PricingProgramType__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Base</fullName>
                </value>
                <value>
                    <fullName>Base_w_no_Price_Increase</fullName>
                </value>
                <value>
                    <fullName>Base_w_Qty_Pricing</fullName>
                </value>
                <value>
                    <fullName>Base_w_Support_Plus</fullName>
                </value>
                <value>
                    <fullName>Chart</fullName>
                </value>
                <value>
                    <fullName>Price_List</fullName>
                </value>
                <value>
                    <fullName>Base_w_Model_Pricing</fullName>
                </value>
                <value>
                    <fullName>Standard</fullName>
                </value>
                <value>
                    <fullName>Standrad_w_Exception</fullName>
                </value>
                <value>
                    <fullName>Standard_w_TPP</fullName>
                </value>
                <value>
                    <fullName>GSA</fullName>
                </value>
                <value>
                    <fullName>Army</fullName>
                </value>
                <value>
                    <fullName>NAF</fullName>
                </value>
                <value>
                    <fullName>Large_Package</fullName>
                </value>
                <value>
                    <fullName>New_Construction_Renovation_LP</fullName>
                </value>
                <value>
                    <fullName>Market_Chart</fullName>
                </value>
                <value>
                    <fullName>Small_Package</fullName>
                </value>
                <value>
                    <fullName>Demo</fullName>
                </value>
                <value>
                    <fullName>Southern_Demo</fullName>
                </value>
                <value>
                    <fullName>First_Tee</fullName>
                </value>
                <value>
                    <fullName>Equipment_Partnership_0-6_Months</fullName>
                </value>
                <value>
                    <fullName>Equipment_Partnership_7-9_Months</fullName>
                </value>
                <value>
                    <fullName>Equipment_Partnership_10-18_Months</fullName>
                </value>
                <value>
                    <fullName>Stock_Order_Demo_Program</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PricingProgramType__c</fullName>
        <label>Pricing Program Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Support Chart</fullName>
                </value>
                <value>
                    <fullName>Corporate Account</fullName>
                </value>
                <value>
                    <fullName>Performance Part</fullName>
                </value>
                <value>
                    <fullName>State Contract</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Toro Pricing Program</label>
    <nameField>
        <label>Toro Pricing Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Toro Pricing Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Toro_PricingProgramEligibility__c.object
<CustomObject>
    <description>Toro Pricing Program Eligibility Junction</description>
    <fields>
        <fullName>Distributor__c</fullName>
        <label>Distributor</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Toro Pricing Program Eligibilities</relationshipLabel>
        <relationshipName>Toro_Pricing_Program_Eligibilities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PricingProgram__c</fullName>
        <label>Toro Pricing Program</label>
        <referenceTo>Toro_PricingProgram__c</referenceTo>
        <relationshipLabel>Toro Pricing Program Eligibilities</relationshipLabel>
        <relationshipName>Toro_Pricing_Program_Eligibilities</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Toro Pricing Program Eligibility</label>
    <nameField>
        <displayFormat>PPE-{0000}</displayFormat>
        <label>Toro Pricing Program Eligibility Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Toro Pricing Program Eligibilities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/User_Distributor__c.object
<CustomObject>
    <fields>
        <fullName>Comm_Dist__c</fullName>
        <label>Comm Dist</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>140</fullName>
                </value>
                <value>
                    <fullName>163</fullName>
                </value>
                <value>
                    <fullName>169</fullName>
                </value>
                <value>
                    <fullName>203</fullName>
                </value>
                <value>
                    <fullName>225</fullName>
                </value>
                <value>
                    <fullName>266</fullName>
                </value>
                <value>
                    <fullName>269</fullName>
                </value>
                <value>
                    <fullName>280</fullName>
                </value>
                <value>
                    <fullName>326</fullName>
                </value>
                <value>
                    <fullName>328</fullName>
                </value>
                <value>
                    <fullName>370</fullName>
                </value>
                <value>
                    <fullName>374</fullName>
                </value>
                <value>
                    <fullName>420</fullName>
                </value>
                <value>
                    <fullName>444</fullName>
                </value>
                <value>
                    <fullName>455</fullName>
                </value>
                <value>
                    <fullName>486</fullName>
                </value>
                <value>
                    <fullName>487</fullName>
                </value>
                <value>
                    <fullName>492</fullName>
                </value>
                <value>
                    <fullName>495</fullName>
                </value>
                <value>
                    <fullName>502</fullName>
                </value>
                <value>
                    <fullName>571</fullName>
                </value>
                <value>
                    <fullName>580</fullName>
                </value>
                <value>
                    <fullName>692</fullName>
                </value>
                <value>
                    <fullName>699</fullName>
                </value>
                <value>
                    <fullName>801</fullName>
                </value>
                <value>
                    <fullName>9810</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Distributor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The commercial distributor head office account</description>
        <inlineHelpText>The commercial distributor this user is accosiated</inlineHelpText>
        <label>Distributor</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>User Distributor</relationshipLabel>
        <relationshipName>User_Distributor</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the user table</description>
        <inlineHelpText>Select the user that will be tied to the distributor</inlineHelpText>
        <label>User Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>User_Distributor</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User Distributor</label>
    <nameField>
        <label>User Distributor</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Distributor</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ToroPricingProgramEligibility.cls
public with sharing class ToroPricingProgramEligibility {
	private static List<Toro_PricingProgram__c> retrieveChartStatePricingProgramsForDistributor(Id distributor) {
		system.debug(logginglevel.info, ' retrieveChartStatePricingProgramsForDistributor= ' + distributor);
		List<Toro_PricingProgram__c> result = new List<Toro_PricingProgram__c>();
		List<Toro_PricingProgramEligibility__c> programs = [Select PricingProgram__r.IsTaxSupported__c, PricingProgram__r.IsFirstTee__c, 
													PricingProgram__r.MinimumTractionUnits__c, PricingProgram__r.OverriddenPriceList__c, 
													PricingProgram__r.AllowSupportPlus__c, PricingProgram__r.PricingProgramStyle__c, 
													PricingProgram__r.PricingProgramType__c, PricingProgram__r.ExternalId__c, PricingProgram__r.Name,
													PricingProgram__r.Exclude__c, PricingProgram__r.ApplicableProducts__c, PricingProgram__c
													From Toro_PricingProgramEligibility__c where Distributor__c = :distributor and PricingProgram__r.IsFirstTee__c = FALSE and PricingProgram__r.CORPORATE_ACCOUNT__C=null];
		system.debug(logginglevel.info, ' programs size= ' + programs.size());
		for(Toro_PricingProgramEligibility__c e : programs) {
			result.add(new Toro_PricingProgram__c(Id=e.PricingProgram__c, Name=e.PricingProgram__r.Name,IsTaxSupported__c = e.PricingProgram__r.IsTaxSupported__c,
													IsFirstTee__c = e.PricingProgram__r.IsFirstTee__c,MinimumTractionUnits__c = e.PricingProgram__r.MinimumTractionUnits__c,
													OverriddenPriceList__c = e.PricingProgram__r.OverriddenPriceList__c,AllowSupportPlus__c = e.PricingProgram__r.AllowSupportPlus__c,
													PricingProgramStyle__c = e.PricingProgram__r.PricingProgramStyle__c,ExternalId__c = e.PricingProgram__r.ExternalId__c,
													Exclude__c = e.PricingProgram__r.Exclude__c));		
		}
		system.debug(logginglevel.info, ' result size= ' + result.size());
		return result;
														
	}
	private static List<Toro_PricingProgram__c> retrieveOtherProgramsForCustomerAccount(Account customer, List<Toro_PricingProgram__c> pricingPrograms) {
		system.debug(logginglevel.info, 'retrieveOtherProgramsForCustomerAccount ');
		List<Toro_PricingProgram__c> result = pricingPrograms;
		Id customerId = customer.Id;
		List<Toro_PricingProgram__c> corporateAccountPP = [select Id, Name, IsTaxSupported__c, IsFirstTee__c, MinimumTractionUnits__c,OverriddenPriceList__c, AllowSupportPlus__c, PricingProgramStyle__c, ExternalId__c, Exclude__c from Toro_PricingProgram__c where Corporate_Account__c in (select CPS_Parent_Account__c from account where id =  :customerId)];
		system.debug(logginglevel.info, 'corporateAccountPP = ' + corporateAccountPP);
		result.addAll(corporateAccountPP);
		
		//add stansdard-alone pricing program
		
		List<Toro_PricingProgramEligibility__c> programs = [Select PricingProgram__r.IsTaxSupported__c, PricingProgram__r.IsFirstTee__c, 
													PricingProgram__r.MinimumTractionUnits__c, PricingProgram__r.OverriddenPriceList__c, 
													PricingProgram__r.AllowSupportPlus__c, PricingProgram__r.PricingProgramStyle__c, 
													PricingProgram__r.PricingProgramType__c, PricingProgram__r.ExternalId__c, PricingProgram__r.Name,
													PricingProgram__r.Exclude__c, PricingProgram__r.ApplicableProducts__c, PricingProgram__c
													From Toro_PricingProgramEligibility__c where Distributor__c = :customer.Id and PricingProgram__r.IsFirstTee__c = FALSE];
		system.debug(logginglevel.info, ' programs size= ' + programs.size());
		for(Toro_PricingProgramEligibility__c e : programs) {
			result.add(new Toro_PricingProgram__c(Id=e.PricingProgram__c, Name=e.PricingProgram__r.Name,IsTaxSupported__c = e.PricingProgram__r.IsTaxSupported__c,
													IsFirstTee__c = e.PricingProgram__r.IsFirstTee__c,MinimumTractionUnits__c = e.PricingProgram__r.MinimumTractionUnits__c,
													OverriddenPriceList__c = e.PricingProgram__r.OverriddenPriceList__c,AllowSupportPlus__c = e.PricingProgram__r.AllowSupportPlus__c,
													PricingProgramStyle__c = e.PricingProgram__r.PricingProgramStyle__c,ExternalId__c = e.PricingProgram__r.ExternalId__c,
													Exclude__c = e.PricingProgram__r.Exclude__c));		
		}
		
		List<String> criteria = new List<String>();
		String query = 'select Id, Name, IsTaxSupported__c, IsFirstTee__c, MinimumTractionUnits__c,OverriddenPriceList__c, AllowSupportPlus__c, PricingProgramStyle__c, ExternalId__c, Exclude__c from Toro_PricingProgram__c  ';
		if(customer.First_Tee__c) {
			criteria.add(' IsFirstTee__c = true ');
		}
		if(customer.Tax_Supported__c) {
			criteria.add(' IsTaxSupported__c = true ');
		}
		if(criteria.size() == 2) {
			query += ' where ' + criteria[0] + ' or ' + criteria[1];		
		} else if(criteria.size() == 1) {
			query += ' where ' + criteria[0];
		}
		if(criteria.size() >0) {
			List<Toro_PricingProgram__c> otherPricingPrograms = Database.query(query);
			if(otherPricingPrograms.size() != 0) {
				result.addAll(otherPricingPrograms);	
			}
		}
		return result;													
	}
	
	public static List<Toro_PricingProgram__c> retrievePricingProgramsForCustomerAccountWithId(Id customerId) {
		account customer = [select id, name, Commercial_Distributor__c, First_Tee__c, Tax_Supported__c from account where id = :customerId];
		return retrievePricingProgramsForCustomerAccount(customer);												
	}
	public static List<Toro_PricingProgram__c> retrievePricingProgramsForCustomerAccount(Account customer) {
		
		system.debug(logginglevel.info, 'retrievePricingProgramsForCustomerAccount.Commercial_Distributor__c --' + customer.Commercial_Distributor__c);
		List<Toro_PricingProgram__c> result = new List<Toro_PricingProgram__c>();
		if(customer.Commercial_Distributor__c != null) {
			system.debug(logginglevel.info, 'distributor =' + customer.Commercial_Distributor__c);
			Id disti = customer.Commercial_Distributor__c;
			result = retrieveChartStatePricingProgramsForDistributor(disti);
		} else {
			Id userId = UserInfo.getUserId();
			system.debug(logginglevel.info, ' user id=' + userId);
			List<User_Distributor__c> distis = [SELECT Id, Name, User_Name__c, Distributor__c, Comm_Dist__c FROM User_Distributor__c where User_Name__c = :userId ];
			system.debug(logginglevel.info, ' disti size= ' + distis.size());
			for(User_Distributor__c disti : distis) {
				result = retrieveChartStatePricingProgramsForDistributor(disti.Distributor__c);
				break;		
			}
		}
		result = retrieveOtherProgramsForCustomerAccount(customer, result);
		return result;
														
	}
	public static List<Toro_PricingProgram__c> retrievePricingProgramsForQuote(Id quoteId) {
		Revvy__MnQuote__c quote = [select id, REVVY__Account__r.Id, REVVY__Account__r.Commercial_Distributor__c, REVVY__Account__r.First_Tee__c, REVVY__Account__r.Tax_Supported__c from revvy__MnQuote__c where id = :quoteId];
		system.debug(logginglevel.info, 'retrievePricingProgramsForQuote');
		return retrievePricingProgramsForCustomerAccount(quote.REVVY__Account__r);
	}  
	public static List<ToroSelectOption> retrievePricingProgramOptions(Id quoteId) {
		List<ToroSelectOption> ret = new List<ToroSelectOption>();
		system.debug(logginglevel.info, 'retrievePricingProgramOptions');
		List<Toro_PricingProgram__c> ppList = retrievePricingProgramsForQuote(quoteId);
		
		for(Toro_PricingProgram__c pp : ppList) {
	        //ret.add(new ToroSelectOption(pp.name, pp.name));
	        system.debug(logginglevel.info, 'retrievePricingProgramOptions ' + pp.ExternalId__c + ' ' + pp.PricingProgramStyle__c + ' ' + pp.name);
	        ret.add(new ToroSelectOption(pp.ExternalId__c+ ';' + pp.PricingProgramStyle__c, pp.name));
        }
		return ret;
	}  
}