objects/REVVY__MnQuote__c.object
<CustomObject>
    <fields>
        <fullName>Gross_Profit_Percent__c</fullName>
        <description>Pricing Method: Gross Profit %</description>
        <label>Gross Profit %</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>SP_Total_Extended_DNET__c</fullName>
        <description>Field &quot;Support Plus Total Extended DNET&quot; is used in support plus page</description>
        <inlineHelpText>Net impact on the DNet based on the use of SP+ on Configured product</inlineHelpText>
        <label>Support Plus Total Extended DNET</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Toro_Blended_Percent_of_DN__c</fullName>
        <label>% of DN</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Toro_Support_Plus_Allowance__c</fullName>
        <description>Toro Support Plus Allowance</description>
        <inlineHelpText>Allowable Program Support Dollars Based on Program</inlineHelpText>
        <label>Toro Support Plus Allowance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Award__c</fullName>
        <label>Ext Award</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

objects/REVVY__MnQuoteItem__c.object
<CustomObject>
    <fields>
        <fullName>Extended_Award_Price__c</fullName>
        <formula>Award_Price__c *  REVVY__Quantity__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Extended Award Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Gross_Profit_Percent__c</fullName>
        <formula>Gross_Profit_Value__c /  Total_Award_price__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Gross Profit %</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Pricing_Program__c</fullName>
        <description>Store value of &quot;Pricing Program&quot; selected by user from &quot;Choose Pricing Program&quot; page. This value is applied to all quote items in this quote.</description>
        <label>Pricing Program</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

classes/ToroQuoteItemEmailController.cls
global class ToroQuoteItemEmailController {
    
    global String quoteId {
    	get;
    	set;
    }
    
    global REVVY__MnQuote__c getQuoteData() {
    	REVVY__MnQuote__c quote = new REVVY__MnQuote__c();
		List<REVVY__MnQuote__c> qList = [Select Id, Total_Award__c, Pricing_Program__c
		                                      , Toro_Blended_Percent_of_DN__c, Gross_Profit_Percent__c
		                                      , Toro_Support_Plus_Allowance__c, SP_Total_Extended_DNET__c
		                                	From REVVY__MnQuote__c
		                                  Where Id = :quoteId
		                                ];    	
		if(qlist!=null && qList.size()>0) {
			quote = qlist[0];
		}
    	return quote;
    }
    
    global List<REVVY__MnQuoteItem__c> getRetrieveQuoteItem() {
    	List<REVVY__MnQuoteItem__c> qiList = new List<REVVY__MnQuoteItem__c>();
    	System.debug('>>> ToroQuoteItemEmailController retrieveQuoteItem quoteId =' + quoteId);
    	
		String query = ' Select REVVY__Product_ID_F__c, REVVY__Catalog_Node__c, REVVY__Catalog_Node__r.Name, REVVY__Quantity__c, Quote_Item_Extension__c, Quote_Item_Extension__r.Extended_Award_Price__c '
		             + ' From REVVY__MnQuoteItem__c where REVVY__Quote__c = :quoteId';
    	System.debug('>>> ToroQuoteItemEmailController retrieveQuoteItem query =' + query);
		qiList = (List<REVVY__MnQuoteItem__c>)	Database.query(query);
    	System.debug('>>> ToroQuoteItemEmailController retrieveQuoteItem qiList =' + qiList);
    	
    	/*
    	String sfield ='';
    	Map<String, Schema.FieldSet> fieldSetMap = Schema.SObjectType.REVVY__MnQuoteItem__c.fieldSets.getMap();
    	if(fieldSetMap!=null && fieldSetMap.containsKey('EmailTemplate')) {
    		Schema.FieldSet fs = fieldSetMap.get('EmailTemplate');
    		List<Schema.FieldSetMember> fsMemberList = fs.getFields();
			for(Schema.FieldSetMember f : fsMemberList) {
            	sfield += ',' + f.getFieldPath();
			}
			sfield = sfield.replaceFirst(',','');    		
    		String query = 'Select ' + sfield + ' From REVVY__MnQuoteItem__c where REVVY__Quote__c = :quoteId';
    		qiList = (List<REVVY__MnQuoteItem__c>)	Database.query(query);
    	}
    	*/
    	return qiList;
    }
}