objects/REVVY__MnCatalogNode__c.object
<CustomObject>
    <fields>
        <fullName>Toro_Product_Type__c</fullName>
        <description>Finished Good: Model or Finished Good information
Non-Stock Material: From SAP: Non-stock material is material that is not held in stock because it is consumed immediately.
Semi-Finished Good: Part</description>
        <label>Toro Product Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Finished Good</fullName>
                </value>
                <value>
                    <fullName>Non-Stock Material</fullName>
                </value>
                <value>
                    <fullName>Semi-Finished Good</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

objects/REVVY__MnStrategy1__c.object
<CustomObject>
    <fields>
        <fullName>ApplicableProductsLong__c</fullName>
        <label>Applicable Products</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>Please enter the unique External ID. Only Alpha-numberical characters are allowed. Ex. You can copy the name of the pricing program and remove all spaces and special characters.</inlineHelpText>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SelectProduct__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to lookup a product</description>
        <label>Select Product</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Enter the Traction unit name or ID</errorMessage>
            <filterItems>
                <field>REVVY__MnCatalogNode__c.REVVY__Type__c</field>
                <operation>equals</operation>
                <value>Product</value>
            </filterItems>
            <filterItems>
                <field>REVVY__MnCatalogNode__c.Toro_Product_Type__c</field>
                <operation>equals</operation>
                <value>Finished Good</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>REVVY__MnCatalogNode__c</referenceTo>
        <relationshipLabel>Pricing Programs</relationshipLabel>
        <relationshipName>PricingPrograms_mp</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

classes/ToroPricingProgramProdSelTest.cls
@isTest
private class ToroPricingProgramProdSelTest {

	@TestSetup static void setupTestData() {
		ToroTestData.loadTestData();

		Revvy__MnStrategy1__c pricingProgram = [
			SELECT
				Id, ApplicableProductsLong__c
			FROM
				Revvy__MnStrategy1__c
			WHERE
				ExternalId__c = 'STILargePackageProgram'
		];

		List<Revvy__MnCatalogNode__c> products = [
			SELECT
				Revvy__Id__c
			FROM
				Revvy__MnCatalogNode__c
			WHERE
				Revvy__Type__c = 'Product'
		];

		String applicableProducts = '';
		for (Revvy__MnCatalogNode__c product : products) {
			applicableProducts += product.Revvy__Id__c + ',';
		}

		pricingProgram.ApplicableProductsLong__c = applicableProducts.removeEnd(',');
		update pricingProgram;
	}

	@isTest static void test_pricing_program_line_product_selector() {
		Revvy__MnStrategy1__c pricingProgram = [SELECT Id, ApplicableProductsLong__c FROM Revvy__MnStrategy1__c WHERE ExternalId__c = 'STILargePackageProgram'];
		final String previousApplicableProducts = pricingProgram.ApplicableProductsLong__c;

		ApexPages.Standardcontroller stdController = new ApexPages.Standardcontroller(pricingProgram);
		ToroPricingProgramProdSel controller = new ToroPricingProgramProdSel(stdController);

		Integer expectedNumberOfSelectedProducts = [SELECT Revvy__Id__c FROM Revvy__MnCatalogNode__c WHERE Revvy__Type__c = 'Product'].size();
		System.assertEquals(expectedNumberOfSelectedProducts, controller.selectedProducts.size());

		// set to applicable products to 'All'
		controller.allProductsSelected = true;
		controller.toggleAllProducts();
		pricingProgram = [SELECT ApplicableProductsLong__c FROM Revvy__MnStrategy1__c WHERE Id = :pricingProgram.Id LIMIT 1];
		System.assertEquals('All', pricingProgram.ApplicableProductsLong__c);

		// switch applicable products to previously selected
		controller.allProductsSelected = false;
		controller.toggleAllProducts();
		pricingProgram = [SELECT ApplicableProductsLong__c FROM Revvy__MnStrategy1__c WHERE Id = :pricingProgram.Id LIMIT 1];
		System.assertEquals(previousApplicableProducts, pricingProgram.ApplicableProductsLong__c);

		// delete a product
		controller.toBeDeleted = pricingProgram.ApplicableProductsLong__c.split(',')[0];
		controller.deleteProduct();
		pricingProgram = [SELECT ApplicableProductsLong__c FROM Revvy__MnStrategy1__c WHERE Id = :pricingProgram.Id LIMIT 1];
		System.assert(!pricingProgram.ApplicableProductsLong__c.contains(controller.toBeDeleted));

		Boolean containsDeletedProduct = false;
		for (ToroPricingProgramProdSel.Wrapper selectedProduct : controller.selectedProducts) {
			if (selectedProduct.revvyId == controller.toBeDeleted) {
				containsDeletedProduct = true;
			}
		}
		System.assert(!containsDeletedProduct);

		// add a product
		Revvy__MnCatalogNode__c productToBeAdded = [SELECT Id, Revvy__Id__c FROM Revvy__MnCatalogNode__c WHERE Revvy__Id__c = :controller.toBeDeleted];
		productToBeAdded.Toro_Product_Type__c='Finished Good';
		update productToBeAdded;
		//controller.dummyProduct.REVVY__Parent__c = productToBeAdded.Id;
		controller.pricingProgram.SelectProduct__c = productToBeAdded.Id;
		controller.addProduct();
		pricingProgram = [SELECT ApplicableProductsLong__c FROM Revvy__MnStrategy1__c WHERE Id = :pricingProgram.Id LIMIT 1];
		System.assert(pricingProgram.ApplicableProductsLong__c.contains(productToBeAdded.Revvy__Id__c));
	}
}