objects/REVVY__MnCatalogNode__c.object
<CustomObject>
    <fields>
        <fullName>Toro_Product_Type__c</fullName>
        <description>Finished Good: Model or Finished Good information
Non-Stock Material: From SAP: Non-stock material is material that is not held in stock because it is consumed immediately.
Semi-Finished Good: Part</description>
        <label>Toro Product Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Finished Good</fullName>
                </value>
                <value>
                    <fullName>Non-Stock Material</fullName>
                </value>
                <value>
                    <fullName>Semi-Finished Good</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

objects/REVVY__MnQuote__c.object
<CustomObject>
    <fields>
        <fullName>Award_Price__c</fullName>
        <description>Quote Award Price equals sum of quote items&apos; total award price</description>
        <label>Award Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Toro_Blended_Percent_of_DN__c</fullName>
        <label>% of DN</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Toro_Total_DNet__c</fullName>
        <label>Ext DNet</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

objects/REVVY__MnStrategy1__c.object
<CustomObject>
    <fields>
        <fullName>Blended_DNet_Threshold__c</fullName>
        <description>Threshold for blended DNet %</description>
        <label>Blended DNet % Threshold</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>OutCrossThreshold__c</fullName>
        <description>Minimum dollar amount threshold for Large Package that has OutCross.</description>
        <label>OutCross Threshold</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

objects/REVVY__MnStrategy4__c.object
<CustomObject>
    <fields>
        <fullName>Adjusted_Quantity__c</fullName>
        <description>Holds quantity adjusted by Support Plus</description>
        <label>QTY</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Award_Price__c</fullName>
        <label>AWARD</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>DNet_Price__c</fullName>
        <label>DNet</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product_Name__c</fullName>
        <formula>IF(  ISBLANK(Description__c), QuoteItem__r.REVVY__Catalog_Node__r.REVVY__LocaleName_F__c, Description__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>DESCRIPTION</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>REVVY__MnCatalogNode__c</referenceTo>
        <relationshipLabel>Toro Quote Item</relationshipLabel>
        <relationshipName>Toro_Quote_Item_mp</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <formula>QuoteItem__r.REVVY__Quantity__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>QTY</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
</CustomObject>

classes/CMnQuoteUtilTest.cls
@isTest
private class CMnQuoteUtilTest {
	@TestSetup static void setupTestData() {
		ToroTestData.loadTestData();
		ToroTestData.loadQuoteTestData();

		List<Revvy__MnStrategy4__c> toroQuoteItems = [
			SELECT
				Award_Price__c
				, DNet_Price__c
			FROM
				Revvy__MnStrategy4__c
		];

		for (Revvy__MnStrategy4__c tqi : toroQuoteItems) {
			tqi.Award_Price__c = 90;
			tqi.DNet_Price__c = 100;
		}

		update toroQuoteItems;
	}
	@isTest static void test_get_new_guid() {
		System.assert(CMnQuoteUtil.getNewGuid() != null);
		List<Revvy__MnStrategy4__c> toroQuoteItems = [
			SELECT
				Product__r.Toro_Product_Type__c,Adjusted_Quantity__c,Product_Name__c, Product__r.Name, Product__r.Id, Quantity__c
			FROM
				Revvy__MnStrategy4__c
		];
		CMnQuoteUtil.getNumberOfTractionUnits(toroQuoteItems);
		CMnQuoteUtil.checkForOutCrossProducts(toroQuoteItems);
		toroQuoteItems[0].Product__r.Name = 'OUTCROSS' + toroQuoteItems[0].Product__r.Name;
		update toroQuoteItems[0].Product__r;
		toroQuoteItems = [
			SELECT
				Product__r.Toro_Product_Type__c,Product_Name__c
			FROM
				Revvy__MnStrategy4__c
		];
		system.debug('-------'+toroQuoteItems);
		CMnQuoteUtil.checkForOutCrossProducts(toroQuoteItems);
		//CMnQuoteUtil.checkIfApprovalNeeded();
	}

	@isTest static void test_default_decimal() {
		System.assertEquals(10, CMnQuoteUtil.defaultDecimal(10));
		System.assertEquals(0, CMnQuoteUtil.defaultDecimal(null));
	}

	@isTest static void test_get_quote_query() {
		String extraFields = '';
		System.assert(CMnQuoteUtil.getQuoteQuery(extraFields) != null);
	}
	
	@isTest static void test_checkIfApprovalNeeded() {
		Test.StartTest();
		CMnQuoteUtil.getDefaultPriceList();
	  	Revvy__MnQuote__c quote = [select Id from Revvy__MnQuote__c limit 1];
	  	ToroLargePackagePricingProgramHelper helper = new ToroLargePackagePricingProgramHelper();
	  	ToroPricingProgramData ppd = new ToroPricingProgramData('MarketSupportChartLargePackage;Large_Package');
		helper.initialize(quote.Id);
		helper.quoteItems[0].Product__r.name='OUTCROSS';
		
		List<REVVY__MnStrategy1__c> pricngPrograms = [select id from REVVY__MnStrategy1__c ];
		for(REVVY__MnStrategy1__c l : pricngPrograms) {
			l.OutCrossThreshold__c = 1000;	
			l.Blended_DNet_Threshold__c=1000;
		}
		update pricngPrograms;
		ToroCacheManager.refreshAllPricingPrograms();
		helper.quote.Toro_Total_DNet__c = 200;
		helper.quote.Toro_Blended_Percent_of_DN__c=200;
		update helper.quote;
		
		CMnQuoteUtil.checkIfApprovalNeeded(helper.quote, 'MarketSupportChartLargePackage', '', helper.quoteItems);	
	  	Test.stopTest();
	}
}