objects/REVVY__MnQuote__c.object
<CustomObject>
    <fields>
        <fullName>Agree_to_Support_Plus_T_C__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Agree to Support Plus Terms &amp; Conditions</description>
        <label>Agree to Support Plus T &amp; C</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DSM_Approved_Amount__c</fullName>
        <label>DSM Approved Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Distributor_Responsibility__c</fullName>
        <description>Distributor Responsibility on Support Plus</description>
        <inlineHelpText>% of SP+ that distributor is responsible for covering</inlineHelpText>
        <label>Distributor Responsibility</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Gross_Profit_Percent__c</fullName>
        <description>Pricing Method: Gross Profit %</description>
        <label>Gross Profit %</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Performance_Part__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Performance Part</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Price_Method__c</fullName>
        <description>Store Price Method selected in pricing page</description>
        <label>Price Method</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pricing_Program_Name__c</fullName>
        <description>Store the name of Pricing Program selected in Pricing Page - Admin use for Pricing Program code</description>
        <label>Pricing Program Name Admin</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SP_Adjusted_Toro_Award__c</fullName>
        <inlineHelpText>Net impact on the Award based on the use of SP+ on Configured product</inlineHelpText>
        <label>SP Adjusted Toro Award</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SP_Ext_Dist_Responsibility__c</fullName>
        <description>Extended Distributor Responsibility is used in support plus page</description>
        <label>SP Ext Dist Responsibility</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SP_Toro_Responsibility__c</fullName>
        <description>Support Plus Toro Responsibility (previously Support_Plus_Rebate__c)</description>
        <label>SP Toro Responsibility</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SP_Total_Extended_DNET__c</fullName>
        <description>Field &quot;Support Plus Total Extended DNET&quot; is used in support plus page</description>
        <inlineHelpText>Net impact on the DNet based on the use of SP+ on Configured product</inlineHelpText>
        <label>Support Plus Total Extended DNET</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Setup_Fee__c</fullName>
        <label>Setup Fee</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Support_Plus__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Support Plus Applied</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Toro_ApprovalReason__c</fullName>
        <label>Toro Approval Reason</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Toro_Award__c</fullName>
        <description>Total Award - TppAllied</description>
        <label>Toro Award</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Toro_Blended_Percent_of_DN__c</fullName>
        <label>% of DN</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Toro_Contribution__c</fullName>
        <inlineHelpText>Amount of SP+ to be claimed from Toro</inlineHelpText>
        <label>Toro Contribution</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Toro_Rollup_DNET__c</fullName>
        <label>Toro Rollup DNET</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Toro_Rollup_DNetWOTPPAllied__c</fullName>
        <description>Rollup over field &quot;DNet Without TPP and Allied&quot; on Quote Item</description>
        <label>Toro Total Toro DNet Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Toro_Support_Plus_Allowance_Used__c</fullName>
        <inlineHelpText>Total Amount of Support Dollars Used Based on Selections</inlineHelpText>
        <label>Toro Support Plus Allowance Used</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Toro_Support_Plus_Allowance__c</fullName>
        <description>Toro Support Plus Allowance</description>
        <inlineHelpText>Allowable Program Support Dollars Based on Program</inlineHelpText>
        <label>Toro Support Plus Allowance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Toro_Total_DNet__c</fullName>
        <label>Ext DNet</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Award_Dollars__c</fullName>
        <description>Pricing Method: Total Award Dollars</description>
        <label>Total Award Dollars</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Extended_DNet__c</fullName>
        <description>Total Extended Dnet Prices</description>
        <label>Total Extended DNet</label>
        <summarizedField>REVVY__MnQuoteItem__c.DNet_Price__c</summarizedField>
        <summaryForeignKey>REVVY__MnQuoteItem__c.REVVY__Quote__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
</CustomObject>

classes/ToroQuoteCache.cls
public with sharing class ToroQuoteCache   {
	public static Revvy__MnQuote__c getQuote(Id quoteId) {
		Revvy__MnQuote__c q = (Revvy__MnQuote__c) Cache.Session.getPartition(ToroCacheManager.constPartitionName).get(quoteId);
		if(q == null) {
			// String quoteQuery = 'select ' + CMnQuoteUtil.getQuoteQuery('Toro_Blended_Percent_of_DN__c,Toro_Total_DNet__c,REVVY__NeedsApproval__c,Toro_ApprovalReason__c,Toro_Rollup_DNetWOTPPAllied__c,Toro_Rollup_DNET__c,Setup_Fee__c,REVVY__Account__r.BillingStateCode, Performance_Part__c, Pricing_Program_Name__c, Price_Method__c, Agree_to_Support_Plus_T_C__c, Gross_Profit_Percent__c, Total_Award_Dollars__c,REVVY__Account__c') + ' from Revvy__MnQuote__c where id=:quoteId';
			String quoteQuery = 'select ' + CMnQuoteUtil.getQuoteQuery('Id,Name,Is_Dirty__c,Setup_Fee_Overridden__c,Toro_Blended_Percent_of_DN__c,Toro_Total_DNet__c,REVVY__NeedsApproval__c,Toro_ApprovalReason__c,Toro_Rollup_DNetWOTPPAllied__c,Toro_Rollup_DNET__c,Setup_Fee__c,REVVY__Account__r.BillingStateCode, Performance_Part__c, Pricing_Program_Name__c, Price_Method__c, Agree_to_Support_Plus_T_C__c, Gross_Profit_Percent__c, Total_Award_Dollars__c,REVVY__Account__c,Toro_Award__c,SP_Adjusted_Toro_Award__c,Toro_Support_Plus_Allowance__c,Toro_Support_Plus_Allowance_Used__c,Toro_Blended_Percent_of_DN__c,SP_Toro_Responsibility__c,SP_Ext_Dist_Responsibility__c,SP_Adjusted_Ext_Award__c,SP_Total_Extended_DNET__c,Support_Plus__c,Toro_Contribution__c,DSM_Approved_Amount__c,CurrencyISOCode,Distributor_Responsibility__c,') + ' from Revvy__MnQuote__c where id=:quoteId';
        	//String quoteQuery = 'select ' + CMnQuoteUtil.getQuoteQuery('Toro_Rollup_DNetWOTPPAllied__c,Total_Extended_DNet__c,Toro_Rollup_DNET__c,Setup_Fee__c, Toro_Support_Plus_Allowance__c,  SP_Toro_Responsibility__c, SP_Ext_Dist_Responsibility__c, SP_Total_Extended_DNET__c,name,REVVY__Account__r.BillingStateCode, Performance_Part__c, Pricing_Program_Name__c, Price_Method__c, Agree_to_Support_Plus_T_C__c') + ' from Revvy__MnQuote__c where id=:quoteId';
        	system.debug('ToroQuoteCache =' + quoteQuery);
        	q = (Revvy__MnQuote__c) Database.query(quoteQuery);
        	system.debug('ToroQuoteCache =' + q);
		}
		putQuote(q);
		return q;
	}
	public static void putQuote(Revvy__MnQuote__c quote) {
		Cache.Session.getPartition(ToroCacheManager.constPartitionName).put(quote.Id, quote);
	}
}