objects/REVVY__MnStrategy1__c.object
<CustomObject>
    <fields>
        <fullName>ApplicableProducts__c</fullName>
        <label>Applicable Products</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Exclude__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Exclude From Display</description>
        <inlineHelpText>Exclude From Display</inlineHelpText>
        <label>Exclude</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>Please enter the unique External ID. Only Alpha-numberical characters are allowed. Ex. You can copy the name of the pricing program and remove all spaces and special characters.</inlineHelpText>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsFirstTee__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is this a first tee pricing program?  This flag is used in pricing program eligibility logic.</description>
        <label>Is First Tee</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsTaxSupported__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is this a tax supported pricing program? This flag is used in pricing program eligibility logic.</description>
        <label>Is Tax Supported</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MinimumThreshold__c</fullName>
        <description>Minimum threshold for a pricing program to be seen in pricing program pick list.</description>
        <label>Minimum Package Threshold</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MinimumTractionUnits__c</fullName>
        <description>Used by Small Package Restriction:
Package must be &gt;$50,000 at DN AND a minimum of 2 traction units.</description>
        <label>Minimum Traction Units</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OutCrossThreshold__c</fullName>
        <description>Minimum dollar amount threshold for Large Package that has OutCross.</description>
        <label>OutCross Threshold</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>OverriddenPriceList__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Overridden Price List</label>
        <referenceTo>REVVY__MnPriceList__c</referenceTo>
        <relationshipLabel>Toro Pricing Programs</relationshipLabel>
        <relationshipName>Toro_Pricing_Programs_mp</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PricingProgramStyle__c</fullName>
        <label>Pricing Program Style</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>PricingProgramType__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Base</fullName>
                </value>
                <value>
                    <fullName>Base_w_no_Price_Increase</fullName>
                </value>
                <value>
                    <fullName>Base_w_Qty_Pricing</fullName>
                </value>
                <value>
                    <fullName>Base_w_Support_Plus</fullName>
                </value>
                <value>
                    <fullName>Chart</fullName>
                </value>
                <value>
                    <fullName>Price_List</fullName>
                </value>
                <value>
                    <fullName>Base_w_Model_Pricing</fullName>
                </value>
                <value>
                    <fullName>Standard</fullName>
                </value>
                <value>
                    <fullName>Standrad_w_Exception</fullName>
                </value>
                <value>
                    <fullName>Standard_w_TPP</fullName>
                </value>
                <value>
                    <fullName>GSA</fullName>
                </value>
                <value>
                    <fullName>Army</fullName>
                </value>
                <value>
                    <fullName>NAF</fullName>
                </value>
                <value>
                    <fullName>Large_Package</fullName>
                </value>
                <value>
                    <fullName>New_Construction_Renovation_LP</fullName>
                </value>
                <value>
                    <fullName>Market_Chart</fullName>
                </value>
                <value>
                    <fullName>Small_Package</fullName>
                </value>
                <value>
                    <fullName>Demo</fullName>
                </value>
                <value>
                    <fullName>Southern_Demo</fullName>
                </value>
                <value>
                    <fullName>First_Tee</fullName>
                </value>
                <value>
                    <fullName>Equipment_Partnership_0-6_Months</fullName>
                </value>
                <value>
                    <fullName>Equipment_Partnership_7-9_Months</fullName>
                </value>
                <value>
                    <fullName>Equipment_Partnership_10-18_Months</fullName>
                </value>
                <value>
                    <fullName>Stock_Order_Demo_Program</fullName>
                </value>
                <value>
                    <fullName>Equipment_Partnership</fullName>
                </value>
                <value>
                    <fullName>Base_w_Quantity_Mdl_Pricing</fullName>
                    <label>Base w qty model pricing</label>
                </value>
                <value>
                    <fullName>Performance_Part</fullName>
                    <label>Performance Part</label>
                </value>
                <value>
                    <fullName>Base_w_Award_Accessories</fullName>
                </value>
                <value>
                    <fullName>Base_w_Model_Qty_Pricing</fullName>
                </value>
                <value>
                    <fullName>Standard_Support_Chart</fullName>
                    <label>Standard Support Chart</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PricingProgramType__c</fullName>
        <label>Pricing Program Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Support Chart</fullName>
                </value>
                <value>
                    <fullName>Corporate Account</fullName>
                </value>
                <value>
                    <fullName>Performance Part</fullName>
                </value>
                <value>
                    <fullName>State Contract</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sequence__c</fullName>
        <label>Sequence</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Setup_Fee__c</fullName>
        <label>Setup Fee</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
</CustomObject>

objects/REVVY__MnStrategy2__c.object
<CustomObject>
    <fields>
        <fullName>ApplicableProducts__c</fullName>
        <label>Applicable Products</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Award_Price_as_a_Percent_of_DN__c</fullName>
        <label>Award Price as a Percent of DN(%)</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Distributor_Margin__c</fullName>
        <label>Distributor Margin(%)</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Fee_Percentage__c</fullName>
        <label>Fee Percentage</label>
        <precision>11</precision>
        <scale>4</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Max_Qty__c</fullName>
        <description>Upper bound of a quantity range</description>
        <label>Max Qty</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Min_Qty__c</fullName>
        <description>Lower bound of a quantity tier.</description>
        <label>Min Qty</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Off_Mfg_Sugg_Ttl__c</fullName>
        <label>Off Mfg. Sugg. Rtl(%)</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Part_Percentage__c</fullName>
        <label>Part Percentage</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>PricingProgram__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Points to Pricing Program</description>
        <label>Pricing Program</label>
        <referenceTo>REVVY__MnStrategy1__c</referenceTo>
        <relationshipLabel>Strategy 2</relationshipLabel>
        <relationshipName>PricingProgramLines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pricing_1__c</fullName>
        <label>Pricing 1</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Pricing_2__c</fullName>
        <label>Pricing 2</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Rebate_as_a_Percent_of_DN__c</fullName>
        <label>Rebate as a Percent of DN(%)</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Sequence__c</fullName>
        <description>Evaluation Sequence. Used in National Account</description>
        <label>Sequence</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Tier__c</fullName>
        <label>Tier</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Tier 1</fullName>
                </value>
                <value>
                    <fullName>Tier 2</fullName>
                </value>
                <value>
                    <fullName>Tier 3</fullName>
                </value>
                <value>
                    <fullName>Parts</fullName>
                </value>
                <value>
                    <fullName>Exception</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

classes/ToroPricingProgramCache.cls
public with sharing class ToroPricingProgramCache implements Cache.CacheBuilder {
	public Object doLoad(String pricingProgramExternalId) {	 
        List<Revvy__MnStrategy1__c> rebates = [Select r.Setup_Fee__c, r.PricingProgramType__c, r.PricingProgramStyle__c, 
        	r.OverriddenPriceList__c, r.OutCrossThreshold__c, r.Name, r.MinimumTractionUnits__c, r.MinimumThreshold__c, 
        	r.IsTaxSupported__c, r.IsFirstTee__c, r.Id, r.ExternalId__c, r.Exclude__c, 
        	(
        		Select Award_Price_as_a_Percent_of_DN__c, Distributor_Margin__c, Fee_Percentage__c, ApplicableProducts__c, 
        		Max_Qty__c, Min_Qty__c, Off_Mfg_Sugg_Ttl__c, Part_Percentage__c, Pricing_1__c, Pricing_2__c, 
        		Rebate_as_a_Percent_of_DN__c, Sequence__c, Tier__c From PricingProgramLines__r 
        		order by Award_Price_as_a_Percent_of_DN__c desc
        	) 
        	From REVVY__MnStrategy1__c r where r.ExternalId__c = :pricingProgramExternalId];
		return rebates[0];  
    }    
}