objects/REVVY__MnPriceListLine__c.object
<CustomObject>
</CustomObject>

objects/REVVY__MnStrategy1__c.object
<CustomObject>
    <fields>
        <fullName>DrivenByGP__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Pay by GP % and not Rebate %</description>
        <label>DrivenByGP</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

objects/REVVY__MnStrategy2__c.object
<CustomObject>
    <fields>
        <fullName>Award_Price__c</fullName>
        <label>Award Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Distributor_Margin__c</fullName>
        <label>Distributor Margin(%)</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>PricingProgram__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Points to Pricing Program</description>
        <label>Pricing Program</label>
        <referenceTo>REVVY__MnStrategy1__c</referenceTo>
        <relationshipLabel>Strategy 2</relationshipLabel>
        <relationshipName>PricingProgramLines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rebate_as_a_Percent_of_DN__c</fullName>
        <label>Rebate as a Percent of DN(%)</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Percent</type>
    </fields>
</CustomObject>

objects/REVVY__MnStrategy4__c.object
<CustomObject>
    <fields>
        <fullName>Award_Price__c</fullName>
        <label>AWARD</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Award_of_DN__c</fullName>
        <description>Store percentage entered by user. This value will be used in calculating award price when price method is &quot;% of DNet&quot;</description>
        <label>% of DNet</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Blended_GP__c</fullName>
        <label>GP %</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Blended_MSRP__c</fullName>
        <label>% Off MSRP</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Blended_Rebate__c</fullName>
        <label>Total Rebate %</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>DNet_Price__c</fullName>
        <label>DNet</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>DrivenByGP__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Driven by GP%</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Extended_Award_Price__c</fullName>
        <description>Extended Award Price = Award_price__c * qty</description>
        <label>EXT AWARD</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Extended_DNet_Price__c</fullName>
        <description>Traction Unit Level DNet</description>
        <label>EXT DNET</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MSRP_Price__c</fullName>
        <label>MSRP</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Off_MSRP__c</fullName>
        <description>Store value of &quot;% off MSRP&quot; entered by user in pricing program page.</description>
        <label>% Off MSRP</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>PricingMethodValue__c</fullName>
        <description>Store pricing method value user enters. Pricing Method could be one of % off MSRP, % of DNet, Total award price, GP$, and GP%.</description>
        <label>Pricing Method Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rebate_as_a_of_DN__c</fullName>
        <description>Store value retrieved from Pricing Program table based on a value of either &quot;% off MSRP&quot; or &quot;% of DNet&quot; entered by a user on &quot;Choose Pricing Program&quot; page.</description>
        <label>RBT%</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Percent</type>
    </fields>
</CustomObject>

objects/REVVY__MnStrategy5__c.object
<CustomObject>
    <fields>
        <fullName>Award_Price__c</fullName>
        <label>AWARD</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>DNet_Price__c</fullName>
        <label>DNET</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Extended_Award_Price__c</fullName>
        <label>EXT AWARD</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Extended_DNet_Price__c</fullName>
        <label>EXT DNET</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MSRP_Price__c</fullName>
        <label>MSRP</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Percent_Off_MSRP__c</fullName>
        <description>Percent Off MSRP</description>
        <label>% Off MSRP</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Percent_of_DNet__c</fullName>
        <description>Percent of DNet</description>
        <label>% of DNet</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>PricingMethodValue__c</fullName>
        <label>Pricing Method Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rebate_as_of_DNet__c</fullName>
        <description>Rebate as % of DNet</description>
        <label>RBT %</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Toro_Quote_Item_2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote Item</label>
        <referenceTo>REVVY__MnStrategy4__c</referenceTo>
        <relationshipLabel>Strategy 5</relationshipLabel>
        <relationshipName>Toro_Quote_Item_Sub_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

classes/ToroNonEligiblePricingProgram.cls
public class ToroNonEligiblePricingProgram extends ToroLargePackagePricingProgramHelper { 
	public override void initialize(Id quoteId) {
		super.initialize(quoteId);
		this.quoteItems = setDefaultFields(this.quoteItems);
	}
	public override List<ToroSelectOption> retrievePricingMethodOptions() { 
		List<ToroSelectOption> ret = new List<ToroSelectOption>();
		if(!Schema.sObjectType.REVVY__MnPriceListLine__c.fields.REVVY__SuggestedPrice__c.isAccessible()) {
			ret.add(new ToroSelectOption('% off MSRP','% off MSRP'));	
		} else {
			ret.add(new ToroSelectOption('% of DNET','% of DNET'));
			ret.add(new ToroSelectOption('% off MSRP','% off MSRP'));
			ret.add(new ToroSelectOption('Total Award $','Total Award $'));
			ret.add(new ToroSelectOption('Gross Profit %','Gross Profit %'));
		}
		return ret;
	}
	/*
	public override List<Revvy__MnStrategy4__c> calculateRebateMarginImpl(Id quoteId, String priceProgram,
															String priceMethod, List<Revvy__MnStrategy4__c> quoteItemList ){
		boolean drivenByGP = false;
		decimal rebate = 0;
		decimal gpPercent = 0;
		List<Revvy__MnStrategy1__c> rebates = new List<Revvy__MnStrategy1__c>{ToroCacheManager.getPricingProgram(priceProgram)}; 
		Map<String, Revvy__MnStrategy2__c> productPricingProgramLineMap = new Map<String, Revvy__MnStrategy2__c>();
		for(Revvy__MnStrategy1__c rh : rebates) {
			drivenByGP = rh.DrivenByGP__c;
			if(rh.PricingProgramLines__r != null) {
				for(Revvy__MnStrategy2__c l : rh.PricingProgramLines__r) {
					rebate = l.Rebate_as_a_Percent_of_DN__c;
					gpPercent = l.Distributor_Margin__c;	
				}
			}
		}
		for(Revvy__MnStrategy4__c qi : quoteItemList) {
			qi.DrivenByGP__c = drivenByGP;
			qi.Rebate_as_a_of_DN__c = rebate;
			
			if('Total Award $'.equalsIgnoreCase(priceMethod)) {
					
			} else if('Gross Profit %'.equalsIgnoreCase(priceMethod)) {
				
			} else if('% off MSRP'.equalsIgnoreCase(priceMethod)) {
				qi.Off_MSRP__c = CMnQuoteUtil.defaultDecimal(qi.Off_MSRP__c);
				qi.msrp_Price__c = CMnQuoteUtil.defaultDecimal(qi.msrp_Price__c);
				qi.Award_Price__c = qi.msrp_Price__c * (100-qi.Off_MSRP__c)/100;
				system.debug('ToroNonEligiblePricingProgram qi.Off_MSRP__c=' + qi.Off_MSRP__c);
				system.debug('ToroNonEligiblePricingProgram qi.msrp_Price__c=' + qi.msrp_Price__c);
				system.debug('ToroNonEligiblePricingProgram qi.Award_Price__c=' + qi.Award_Price__c);	
			} else if('% of DNET'.equalsIgnoreCase(priceMethod)) {
				qi.Award_of_DN__c = CMnQuoteUtil.defaultDecimal(qi.Award_of_DN__c);
				qi.DNet_Price__c = CMnQuoteUtil.defaultDecimal(qi.DNet_Price__c);
				qi.Award_Price__c = qi.DNet_Price__c * qi.Award_of_DN__c/100;
			}
			if (qi.Toro_Quote_Item_Sub_Lines__r != null && qi.Toro_Quote_Item_Sub_Lines__r.size() > 0) {
				
				for (Revvy__MnStrategy5__c qis : qi.Toro_Quote_Item_Sub_Lines__r) {
					qis.Rebate_as_of_DNet__c = rebate;
					qis.Percent_Off_MSRP__c = CMnQuoteUtil.defaultDecimal(qis.Percent_Off_MSRP__c);
					if('Total Award $'.equalsIgnoreCase(priceMethod)) {
				
					} else if('Gross Profit %'.equalsIgnoreCase(priceMethod)) {
						
					} else if('% off MSRP'.equalsIgnoreCase(priceMethod)) {
						qis.Percent_Off_MSRP__c = CMnQuoteUtil.defaultDecimal(qis.Percent_Off_MSRP__c);
						qis.msrp_Price__c = CMnQuoteUtil.defaultDecimal(qis.msrp_Price__c);
						qis.Award_Price__c = qi.msrp_Price__c * (100-qis.Percent_Off_MSRP__c)/100;	
						system.debug('ToroNonEligiblePricingProgram qis.Percent_Off_MSRP__c=' + qis.Percent_Off_MSRP__c);
						system.debug('ToroNonEligiblePricingProgram qis.msrp_Price__c=' + qis.msrp_Price__c);
						system.debug('ToroNonEligiblePricingProgram qis.Award_Price__c=' + qis.Award_Price__c);
					} else if('% of DNET'.equalsIgnoreCase(priceMethod)) {
						qis.Percent_of_DNet__c = CMnQuoteUtil.defaultDecimal(qis.Percent_of_DNet__c);
						qis.DNet_Price__c = CMnQuoteUtil.defaultDecimal(qis.DNet_Price__c);
						qis.Award_Price__c = qi.DNet_Price__c * qis.Percent_of_DNet__c/100;
					}
				}
			}
			
		}
		return quoteItemList;															
	}
	*/
	public override List<Revvy__MnStrategy4__c> setDefaultFields(List<Revvy__MnStrategy4__c> quoteItemList) {
		for(Revvy__MnStrategy4__c qi : quoteItemList) {
			qi.DrivenByGP__c=false;
            qi.Off_MSRP__c = CMnQuoteUtil.defaultDecimal(qi.Off_MSRP__c);
            qi.Award_of_DN__c = CMnQuoteUtil.defaultDecimal(qi.Award_of_DN__c);
            qi.Award_Price__c = CMnQuoteUtil.defaultDecimal(qi.Award_Price__c);
            qi.Extended_Award_Price__c = CMnQuoteUtil.defaultDecimal(qi.Extended_Award_Price__c);
            qi.Blended_GP__c = CMnQuoteUtil.defaultDecimal(qi.Blended_GP__c);
            //qi.Blended_MSRP__c = CMnQuoteUtil.defaultDecimal(qi.Blended_MSRP__c);
            qi.Blended_Rebate__c = CMnQuoteUtil.defaultDecimal(qi.Blended_Rebate__c);
            qi.Extended_DNet_Price__c = CMnQuoteUtil.defaultDecimal(qi.Extended_DNet_Price__c);
			if(!SObjectType.Revvy__MnStrategy4__c.fields.PricingMethodValue__c.isUpdateable()) {
				if(String.isBlank(qi.PricingMethodValue__c)) {
					qi.PricingMethodValue__c='0';		
				}	
			}	
			if (qi.Toro_Quote_Item_Sub_Lines__r != null && qi.Toro_Quote_Item_Sub_Lines__r.size() > 0) {
				for (Revvy__MnStrategy5__c qis : qi.Toro_Quote_Item_Sub_Lines__r) {
					qis.Percent_Off_MSRP__c = CMnQuoteUtil.defaultDecimal(qis.Percent_Off_MSRP__c);
                    qis.Award_Price__c = CMnQuoteUtil.defaultDecimal(qis.Award_Price__c);
                    qis.Extended_Award_Price__c = CMnQuoteUtil.defaultDecimal(qis.Extended_Award_Price__c);
                    qis.Percent_of_DNet__c = CMnQuoteUtil.defaultDecimal(qis.Percent_of_DNet__c);
					if(!SObjectType.Revvy__MnStrategy5__c.fields.PricingMethodValue__c.isUpdateable()) {
						if(String.isBlank(qis.PricingMethodValue__c)) {
							qis.Percent_Off_MSRP__c=0;
							qis.PricingMethodValue__c='0';		
						}
					}
				}
			}
		}	
		return quoteItemList;
	} 
}