objects/REVVY__MnQuote__c.object
<CustomObject>
    <fields>
        <fullName>Pricing_Program_Name__c</fullName>
        <description>Store the name of Pricing Program selected in Pricing Page - Admin use for Pricing Program code</description>
        <label>Pricing Program Name Admin</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

objects/REVVY__MnStrategy1__c.object
<CustomObject>
    <fields>
        <fullName>Determines_Support_Plus_Allowance__c</fullName>
        <label>Determines Support Plus Allowance</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Total DNet Only</fullName>
                    <default>true</default>
                    <label>Total DNet Only</label>
                </value>
                <value>
                    <fullName>Award Only</fullName>
                </value>
                <value>
                    <fullName>Total DNet and Award</fullName>
                    <label>Percent DNet and Award</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>Please enter the unique External ID. Only Alpha-numberical characters are allowed. Ex. You can copy the name of the pricing program and remove all spaces and special characters.</inlineHelpText>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

classes/ToroSupportPlusItemTest.cls
@isTest
private class ToroSupportPlusItemTest {

	@TestSetup static void setup() {
		ToroTestData.loadTestData();
		ToroTestData.loadQuoteTestData();

		REVVY__MnQuote__c quote = [SELECT Pricing_Program_Name__c FROM REVVY__MnQuote__c LIMIT 1];
		quote.Pricing_Program_Name__c = 'MarketSupportChartLargePackage;Large_Package';
		update quote;

		REVVY__MnStrategy1__c pricingProgram = [SELECT Determines_Support_Plus_Allowance__c FROM REVVY__MnStrategy1__c WHERE ExternalId__c = 'MarketSupportChartLargePackage'];
		pricingProgram.Determines_Support_Plus_Allowance__c = ToroSupportPlusHelper.DETERMINES_SP_ALLOWANCE_DNET;
		update pricingProgram;

		insert new Revvy__MnSequenceGen__c(
			  Revvy__ObjectName__c   = 'MnQuoteItem__c'
			, REVVY__CurrentValue__c = 1
		);
	}

	@isTest static void test_constructor() {
		Test.startTest();
		Id quoteId = [SELECT Id FROM REVVY__MnQuote__c LIMIT 1].Id;
		ToroSupportPlusData data = new ToroSupportPlusData(quoteId);
		System.assert(data != null);

		System.assert(data.qiWrappers[0] != null);
		// System.assert(data.qiWrappers[0].distributorResponsibility != null);
		// System.assert(data.qiWrappers[0].qiPricingProgramExtId != null);
		Test.stopTest();
	}



}