objects/REVVY__MnQuote__c.object
<CustomObject>
</CustomObject>

objects/REVVY__MnStrategy1__c.object
<CustomObject>
    <fields>
        <fullName>ExternalId__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>Please enter the unique External ID. Only Alpha-numberical characters are allowed. Ex. You can copy the name of the pricing program and remove all spaces and special characters.</inlineHelpText>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UseDesignatedPriceList__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Use Designated Price List</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

objects/REVVY__MnStrategy4__c.object
<CustomObject>
</CustomObject>

classes/ToroPricingProgramTest.cls
@isTest
private class ToroPricingProgramTest { 
	@TestSetup static void setupTestData() {
		ToroTestData.loadTestData();
		ToroTestData.loadQuoteTestData();
	}
	 @isTest static void unitTest() {
	 	//@TestVisible
		ToroDefaultPricingProgramHelper helper = new ToroDefaultPricingProgramHelper();
		List<Schema.FieldSetMember> fs = helper.getToroQuoteItemDNetFields();
		
		fs = helper.getToroQuoteItemSublineDNetFields(); 
		
		List<ToroSelectOption> options = helper.retrievePricingMethodOptions();
		List<String> apiName =helper.getQuoteFieldAPINames();
		helper.getQuoteFieldAPINameQuery('');
		String query = helper.getToroQuoteFieldAPINameQuery('');
		helper.loadDesignatedPriceList('Demo'); 
		Revvy__MnQuote__c quote = [select Id from Revvy__MnQuote__c limit 1];
		//helper.retrieveSetupFeeQuoteItem(quote.Id);
		//List<Revvy__MnStrategy4__c>
		ToroPricingProgramData ppd = new ToroPricingProgramData('MarketSupportChartLargePackage;Large_Package');
		helper.initialize(quote.Id);
		Revvy__MnStrategy1__c pricingProgram = [select id from Revvy__MnStrategy1__c where externalId__c = 'MarketSupportChartLargePackage' limit 1];
	 	pricingProgram.UseDesignatedPriceList__c=true;
	 	pricingProgram.Previous_Price_Date__c = Date.today();
	 	pricingProgram.Copy_From_Price_Field__c = 'MSRP';
	 	update pricingProgram;
	 	helper.loadMSRPPriceFromPricelist('MarketSupportChartLargePackage;Large_Package',helper.quoteItems);
	 	pricingProgram.Copy_From_Price_Field__c = 'DNET';
	 	update pricingProgram;
	 	helper.loadMSRPPriceFromPricelist('MarketSupportChartLargePackage;Large_Package',helper.quoteItems);
	 }
	
}