objects/REVVY__MnQuote__c.object
<CustomObject>
    <fields>
        <fullName>Setup_Fee__c</fullName>
        <label>Setup Fee</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
</CustomObject>

objects/REVVY__MnStrategy1__c.object
<CustomObject>
    <fields>
        <fullName>Setup_Fee__c</fullName>
        <label>Setup Fee</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
</CustomObject>

objects/REVVY__MnStrategy2__c.object
<CustomObject>
    <fields>
        <fullName>PricingProgram__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Points to Pricing Program</description>
        <label>Pricing Program</label>
        <referenceTo>REVVY__MnStrategy1__c</referenceTo>
        <relationshipLabel>Strategy 2</relationshipLabel>
        <relationshipName>PricingProgramLines</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/REVVY__MnStrategy4__c.object
<CustomObject>
    <fields>
        <fullName>DNet_Price__c</fullName>
        <label>DNet</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MSRP_Price__c</fullName>
        <label>MSRP</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product_Name__c</fullName>
        <formula>IF(  ISBLANK(Description__c), QuoteItem__r.REVVY__Catalog_Node__r.REVVY__LocaleName_F__c, Description__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>DESCRIPTION</label>
        <type>Text</type>
    </fields>
</CustomObject>

objects/REVVY__MnStrategy5__c.object
<CustomObject>
    <fields>
        <fullName>DNet_Price__c</fullName>
        <label>DNET</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MSRP_Price__c</fullName>
        <label>MSRP</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product_Name__c</fullName>
        <formula>Quote_Item_Sub_Line__r.REVVY__Catalog_Node__r.REVVY__LocaleName_F__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>DESCRIPTION</label>
        <type>Text</type>
    </fields>
</CustomObject>

classes/ToroCacheManagerTest.cls
@isTest
private class ToroCacheManagerTest {
	@testSetup static void setupData() {
		ToroTestData.loadTestData();
		ToroTestData.loadQuoteTestData();
	}
	static testMethod void myUnitTest() {
        String largePackageExtId = 'MarketSupportChartLargePackage';
       	Revvy__MnStrategy1__c pp = ToroCacheManager.getPricingProgram(largePackageExtId);
        system.assertEquals('Large Package', pp.name);
        system.assertEquals(21, pp.PricingProgramLines__r.size());
        List<REVVY__MnStrategy4__c> qiExts = [select id, product_name__c, MSRP_Price__c, DNet_Price__c from REVVY__MnStrategy4__c];
        system.assertEquals(4, qiExts.size());
        for(REVVY__MnStrategy4__c qi : qiExts) {
        	system.debug('qi ext = name =' + qi.product_name__c + ' msrp=' + qi.msrp_price__c + ' dnet=' + qi.dnet_price__c );	
        }
        List<REVVY__MnStrategy5__c> qisExts = [select id, product_name__c, MSRP_Price__c, DNet_Price__c from REVVY__MnStrategy5__c];
        for(REVVY__MnStrategy5__c qis : qisExts) {
        	system.debug('qis ext = name =' + qis.product_name__c + ' msrp=' + qis.msrp_price__c + ' dnet=' + qis.dnet_price__c );	
        }
        system.assertEquals(10, qisExts.size());
        
    } 
    static testMethod void testQuoteCache() {
    	REVVY__MnQuote__c q = [select id from  REVVY__MnQuote__c limit 1];
    	q = ToroCacheManager.getQuote(q.Id);
    	system.debug('-------q.Setup_Fee__c=' + q.Setup_Fee__c);
    	q.Setup_Fee__c = 2;
    	
    	q = ToroCacheManager.getQuote(q.Id);
    	system.debug('-------' + q.Setup_Fee__c);
    	system.assert(q.Setup_Fee__c == null);
    	q = ToroCacheManager.refreshQuote(q.Id);
    	system.assert(q.Setup_Fee__c == null);
    	q.Setup_Fee__c = 3;
    	update q;
    	q = ToroCacheManager.getQuote(q.Id);
    	system.assert(q.Setup_Fee__c == 3);
    	
    	//system.assertEquals('Commercial', q.REVVY__Segment__c);
    }   
}