objects/REVVY__MnQuoteItem__c.object
<CustomObject>
    <fields>
        <fullName>Award_Price__c</fullName>
        <label>Award Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Off_MSRP__c</fullName>
        <description>Store value of &quot;% off MSRP&quot; entered by user in pricing program page.</description>
        <label>Percent Off MSRP</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Performance_Parts_Product__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Performance Parts</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Unit_Award_Overridden__c</fullName>
        <defaultValue>false</defaultValue>
        <description>To indicate that Unit Award has been overridden by user</description>
        <label>Unit Award Overridden</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

objects/REVVY__MnQuoteItemSubLine__c.object
<CustomObject>
    <fields>
        <fullName>Award_Price__c</fullName>
        <label>Award Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Performance_Part__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Performance Part</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product_ID2__c</fullName>
        <label>Product ID2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

objects/Toro_PricingProgram__c.object
<CustomObject>
    <fields>
        <fullName>ApplicableProducts__c</fullName>
        <label>Applicable Products</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>PricingProgramType__c</fullName>
        <label>Pricing Program Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Support Chart</fullName>
                </value>
                <value>
                    <fullName>Corporate Account</fullName>
                </value>
                <value>
                    <fullName>Performance Part</fullName>
                </value>
                <value>
                    <fullName>State Contract</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Toro Pricing Program</label>
    <nameField>
        <label>Toro Pricing Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Toro Pricing Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Toro_PricingProgramLine__c.object
<CustomObject>
    <fields>
        <fullName>ApplicableProducts__c</fullName>
        <label>Applicable Products</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PricingProgram__c</fullName>
        <label>Pricing Program</label>
        <referenceTo>Toro_PricingProgram__c</referenceTo>
        <relationshipName>PricingProgramLines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Pricing_1__c</fullName>
        <label>Pricing 1</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Toro Pricing Program Line</label>
    <nameField>
        <label>Toro Pricing Program Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Toro Pricing Program Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ToroPerformancePartPricingProgramHelper.cls
public with sharing class ToroPerformancePartPricingProgramHelper {

	public static void reset(Id quoteId, String priceProgramExternalId, String priceMethod
	                                                      , Boolean bperformancePart
	                                                      , List<REVVY__MnQuoteItem__c> quoteItemList
	                                                      , List<REVVY__MnQuoteItemSubline__c> quoteItemSubLineList) {

		system.debug('+++++++++++++++++ quoteItem' + quoteItemList);
		system.debug('+++++++++++++++++ quoteItemSubLine' + quoteItemSubLineList);
		
		for(REVVY__MnQuoteItem__c qi:quoteItemList) {
			qi.Performance_Parts_Product__c = false;
			qi.Performance_Parts_Product__c = false;
			if(!qi.Unit_Award_Overridden__c) {
	        	qi.Award_Price__c=qi.REVVY__Unit_Price__c = qi.Revvy__Price__c;
			}
	        qi.revvy__freezepricing__c=false;
		}
		if(quoteItemSubLineList!=null) {
			for(REVVY__MnQuoteItemSubline__c qi:quoteItemSubLineList) {
				
				qi.Performance_Part__c = false;
				if(!qi.Unit_Award_Overridden__c) {
		        	qi.Award_Price__c=qi.REVVY__Unit_Price__c = qi.Revvy__Price__c;
				}
		        qi.revvy__freezepricing__c=false;
			}
		
		}
	}    
	
	public static Map<String,Decimal> retrievePerformancePart() {
		Map<String,Decimal> ppMap = new Map<String,Decimal>();
		for(Toro_PricingProgramLine__c rl:[Select Id, ApplicableProducts__c, Pricing_1__c
		                          From Toro_PricingProgramLine__c
		                         Where PricingProgram__r.Name = 'Performance Part'
		                           and PricingProgram__r.PricingProgramType__c = 'Performance Part' ]) {
			ppMap.put(rl.ApplicableProducts__c, rl.Pricing_1__c);                           	
		}
		return ppMap;
	}


	public static void applyPerformancePartForQuoteItem(Boolean bperformancePart, REVVY__MnQuoteItem__c qi, Map<String,Decimal> ppMap) {
		system.debug('+++++++++++++++++ PP quoteItem=' + qi);
		
		qi.Performance_Parts_Product__c = false;
		if(!qi.Unit_Award_Overridden__c) {
        	qi.Award_Price__c=qi.REVVY__Unit_Price__c = qi.Revvy__Price__c;
		}
        qi.revvy__freezepricing__c=false;
		system.debug('+++++++++++++++++ PP QuoteItem bperformancePart=' + bperformancePart);
		if(bperformancePart!=null && bperformancePart
		&& ppMap !=null && ppMap.containsKey(qi.REVVY__Product_ID_F__c)) {
			qi.REVVY__Unit_Price__c = ppMap.get(qi.REVVY__Product_ID_F__c);
			//system.debug('&&&&&&&&&&&&&&&&&&&&&&& PP QuoteItem qi.REVVY__Price__c=' + qi.REVVY__Price__c);
			qi.Performance_Parts_Product__c = true;
            qi.revvy__freezepricing__c=true;
            qi.Off_MSRP__c = 0;
            if(!qi.Unit_Award_Overridden__c) {
            	qi.Award_Price__c =qi.REVVY__Unit_Price__c;
            }
		}
	}   
	
	public static void applyPerformancePartForQuoteItemSubLine(Boolean bperformancePart, REVVY__MnQuoteItemSubline__c qi, Map<String,Decimal> ppMap) {
		system.debug('+++++++++++++++++ Performance Part quoteItem' + qi);
		
		qi.Performance_Part__c = false;
		if(!qi.Unit_Award_Overridden__c) {
        	qi.Award_Price__c=qi.REVVY__Unit_Price__c = qi.Revvy__Price__c;
		}
        qi.revvy__freezepricing__c=false;
		system.debug('+++++++++++++++++ PP QuoteItemSubLine bperformancePart=' + bperformancePart);
		if(bperformancePart!=null && bperformancePart 
		&& ppMap !=null && ppMap.containsKey(qi.Product_ID2__c)) {
			qi.REVVY__Unit_Price__c = ppMap.get(qi.Product_ID2__c);
			system.debug('&&&&&&&&&&&&&&&&&&&&&&& PP QuoteItemSubLine qi.REVVY__Price__c=' + qi.REVVY__Price__c + ' - '+ qi.Product_ID2__c);
			qi.Performance_Part__c = true;
            qi.revvy__freezepricing__c=true;
            if(!qi.Unit_Award_Overridden__c) {
            	qi.Award_Price__c =qi.REVVY__Unit_Price__c;
            }
		}
	}   	    
}