objects/REVVY__MnStrategy1__c.object
<CustomObject>
    <fields>
        <fullName>ApplicableProducts__c</fullName>
        <label>Applicable Products</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>Please enter the unique External ID. Only Alpha-numberical characters are allowed. Ex. You can copy the name of the pricing program and remove all spaces and special characters.</inlineHelpText>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

objects/REVVY__MnStrategy2__c.object
<CustomObject>
    <fields>
        <fullName>ApplicableProducts__c</fullName>
        <label>Applicable Products</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Award_Price_as_a_Percent_of_DN__c</fullName>
        <label>Award Price as a Percent of DN(%)</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Distributor_Margin__c</fullName>
        <label>Distributor Margin(%)</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Off_Mfg_Sugg_Ttl__c</fullName>
        <label>Off Mfg. Sugg. Rtl(%)</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>PricingProgram__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Points to Pricing Program</description>
        <label>Pricing Program</label>
        <referenceTo>REVVY__MnStrategy1__c</referenceTo>
        <relationshipLabel>Strategy 2</relationshipLabel>
        <relationshipName>PricingProgramLines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rebate_as_a_Percent_of_DN__c</fullName>
        <label>Rebate as a Percent of DN(%)</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Percent</type>
    </fields>
</CustomObject>

classes/CMnPriceProgramUtil.cls
public with sharing class CMnPriceProgramUtil {
	public class PriceProgramInfo {
		public map<string, Revvy__MnStrategy1__c> rebateMap {get; set; }
		public map<string, set<String>> rebateApplicableProducts { get; set; }
	}

	public static PriceProgramInfo collectPriceProgram(String priceProgramExternalId) {
		PriceProgramInfo ret = new PriceProgramInfo();
		List<Revvy__MnStrategy1__c> rebates = [Select r.Name, r.ExternalId__c, r.ApplicableProducts__c, 
				(Select Off_Mfg_Sugg_Ttl__c, Award_Price_as_a_Percent_of_DN__c, Rebate_as_a_Percent_of_DN__c, 
				Distributor_Margin__c, ApplicableProducts__c From PricingProgramLines__r) From Revvy__MnStrategy1__c r where name = :priceProgramExternalId];
		map<string, Revvy__MnStrategy1__c> rebateMap = new map<string, Revvy__MnStrategy1__c>();
		map<string, set<String>> rebateApplicableProducts = new map<string, set<String>>();
		for(Revvy__MnStrategy1__c rh : rebates) {
			rebateMap.put(rh.ExternalId__c, rh);
			if(!rebateApplicableProducts.containsKey(rh.ExternalId__c)) {
				rebateApplicableProducts.put(rh.ExternalId__c, new set<String>());	
			}	
			if(string.isNotBlank(rh.ApplicableProducts__c)) {
				String[] parts = rh.ApplicableProducts__c.split(',');
				rebateApplicableProducts.get(rh.ExternalId__c).addAll(parts);	
			}
			
		}
		ret.rebateMap = rebateMap;
		ret.rebateApplicableProducts = rebateApplicableProducts;
		return ret;
	}

	
}