objects/REVVY__MnQuoteItemSubLine__c.object
<CustomObject>
    <fields>
        <fullName>Quote_Item_Sub_Line_Extension__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote Item Sub Line Extension</label>
        <referenceTo>REVVY__MnStrategy5__c</referenceTo>
        <relationshipLabel>Quote Item Sub Line</relationshipLabel>
        <relationshipName>Quote_Item_Sub_Line</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Toro_QuoteItem__c.object
<CustomObject>
    <fields>
        <fullName>External_Id__c</fullName>
        <externalId>true</externalId>
        <label>External_Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Toro Quote Item</label>
    <nameField>
        <displayFormat>TQ-{0000000}</displayFormat>
        <label>Toro Quote Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Toro Quote Item</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Toro_QuoteItem_SubLine__c.object
<CustomObject>
    <fields>
        <fullName>External_Id__c</fullName>
        <externalId>true</externalId>
        <label>External_Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Toro_Quote_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote Item</label>
        <referenceTo>Toro_QuoteItem__c</referenceTo>
        <relationshipLabel>Toro Quote Item Sub Lines</relationshipLabel>
        <relationshipName>Toro_Quote_Item_Sub_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Toro Quote Item Sub Line</label>
    <nameField>
        <displayFormat>TQS-{00000}</displayFormat>
        <label>Toro Quote Item Sub Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Toro Quote Item Sub Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ToroQISLExtensionCreatedBatch.cls
global with sharing class ToroQISLExtensionCreatedBatch implements Database.Batchable<sObject>, Database.stateful {
	String query;
	List<Id> qiExtensionList { get; set; }
	global ToroQISLExtensionCreatedBatch(List<Id> qiExtensions) {
		qiExtensionList = qiExtensions;
		query = 'select id, external_Id__c from Toro_QuoteItem_SubLine__c where id in :qiExtensionList';
	}
	global Database.QueryLocator start(Database.BatchableContext BC) {
    	return Database.getQueryLocator(query);
    }  
    global void execute(Database.BatchableContext BC, List<sObject> scope) {
    	
    	List<REVVY__MnQuoteItemSubLine__c> qis = new List<REVVY__MnQuoteItemSubLine__c>();
    	List<Toro_QuoteItem_SubLine__c> quoteItemList = (List<Toro_QuoteItem_SubLine__c>)scope;
    	/*
    	List<Id> qiSublineIds = new List<Id> ();
    	for(Toro_QuoteItem_SubLine__c tqi : quoteItemList) {
    		qiSublineIds.add(tqi.External_Id__c);	
    	}
    	map<Id, Id> qiIdMap = new map<Id,Id>();
    	for(REVVY__MnQuoteItemSubLine__c qisl : [select id, revvy__quoteitem__c from REVVY__MnQuoteItemSubLine__c where id in :qiSublineIds]) {
    		qiIdMap.put(qisl.Id, qisl.revvy__quoteitem__c);	
    	}
    	*/
    	for(Toro_QuoteItem_SubLine__c tqi : quoteItemList) {
    		qis.add(new REVVY__MnQuoteItemSubLine__c(Id =tqi.External_Id__c, Quote_Item_Sub_Line_Extension__c = tqi.Id));
    		//tqi.Toro_Quote_Item__r = new Toro_Quoteitem__c(External_Id__c = qiIdMap.get(tqi.External_Id__c));		
    	}
    	update qis;	
    	//update quoteItemList;
    	
    }  
    global void finish(Database.BatchableContext BC) {
    	 
    }    
}