objects/REVVY__MnCatalogNode__c.object
<CustomObject>
    <fields>
        <fullName>Toro_Product_Type__c</fullName>
        <description>Finished Good: Model or Finished Good information
Non-Stock Material: From SAP: Non-stock material is material that is not held in stock because it is consumed immediately.
Semi-Finished Good: Part</description>
        <label>Toro Product Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Finished Good</fullName>
                </value>
                <value>
                    <fullName>Non-Stock Material</fullName>
                </value>
                <value>
                    <fullName>Semi-Finished Good</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

objects/REVVY__MnPriceListLine__c.object
<CustomObject>
    <fields>
        <fullName>Toro_Product_Type__c</fullName>
        <formula>TEXT( REVVY__Product__r.Toro_Product_Type__c )</formula>
        <label>Toro Product Type</label>
        <type>Text</type>
    </fields>
</CustomObject>

objects/REVVY__MnQuote__c.object
<CustomObject>
    <fields>
        <fullName>Toro_ApprovalReason__c</fullName>
        <label>Toro Approval Reason</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Toro_ApprovalRequired__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Toro Approval Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Total_Extended_DNet__c</fullName>
        <description>Total Extended Dnet Prices</description>
        <label>Total Extended DNet</label>
        <summarizedField>REVVY__MnQuoteItem__c.DNet_Price__c</summarizedField>
        <summaryForeignKey>REVVY__MnQuoteItem__c.REVVY__Quote__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
</CustomObject>

objects/Toro_PricingProgram__c.object
<CustomObject>
    <fields>
        <fullName>Exclude__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Exclude From Display</description>
        <inlineHelpText>Exclude From Display</inlineHelpText>
        <label>Exclude</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MinimumThreshold__c</fullName>
        <description>Minimum threshold for a pricing program to be seen in pricing program pick list.</description>
        <label>Large Package Minimum Threshold</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MinimumTractionUnits__c</fullName>
        <description>Used by Small Package Restriction:
Package must be &gt;$50,000 at DN AND a minimum of 2 traction units.</description>
        <label>Minimum Traction Units</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OutCrossThreshold__c</fullName>
        <description>Minimum dollar amount threshold for Large Package that has Out Cross.</description>
        <label>Out Cross Threshold</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PricingProgramStyle__c</fullName>
        <label>Pricing Program Style</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>PricingProgramType__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Base</fullName>
                </value>
                <value>
                    <fullName>Base_w_no_Price_Increase</fullName>
                </value>
                <value>
                    <fullName>Base_w_Qty_Pricing</fullName>
                </value>
                <value>
                    <fullName>Base_w_Support_Plus</fullName>
                </value>
                <value>
                    <fullName>Chart</fullName>
                </value>
                <value>
                    <fullName>Price_List</fullName>
                </value>
                <value>
                    <fullName>Base_w_Model_Pricing</fullName>
                </value>
                <value>
                    <fullName>Standard</fullName>
                </value>
                <value>
                    <fullName>Standrad_w_Exception</fullName>
                </value>
                <value>
                    <fullName>Standard_w_TPP</fullName>
                </value>
                <value>
                    <fullName>GSA</fullName>
                </value>
                <value>
                    <fullName>Army</fullName>
                </value>
                <value>
                    <fullName>NAF</fullName>
                </value>
                <value>
                    <fullName>Large_Package</fullName>
                </value>
                <value>
                    <fullName>New_Construction_Renovation_LP</fullName>
                </value>
                <value>
                    <fullName>Market_Chart</fullName>
                </value>
                <value>
                    <fullName>Small_Package</fullName>
                </value>
                <value>
                    <fullName>Demo</fullName>
                </value>
                <value>
                    <fullName>Southern_Demo</fullName>
                </value>
                <value>
                    <fullName>First_Tee</fullName>
                </value>
                <value>
                    <fullName>Equipment_Partnership_0-6_Months</fullName>
                </value>
                <value>
                    <fullName>Equipment_Partnership_7-9_Months</fullName>
                </value>
                <value>
                    <fullName>Equipment_Partnership_10-18_Months</fullName>
                </value>
                <value>
                    <fullName>Stock_Order_Demo_Program</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Toro Pricing Program</label>
    <nameField>
        <label>Toro Pricing Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Toro Pricing Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Toro_PricingProgramLine__c.object
<CustomObject>
    <fields>
        <fullName>Award_Price_as_a_Percent_of_DN__c</fullName>
        <label>Award Price as a Percent of DN(%)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Rebate_as_a_Percent_of_DN__c</fullName>
        <label>Rebate as a Percent of DN(%)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Toro Pricing Program Line</label>
    <nameField>
        <label>Toro Pricing Program Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Toro Pricing Program Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Toro_QuoteItem__c.object
<CustomObject>
    <fields>
        <fullName>Product_Name__c</fullName>
        <formula>QuoteItem__r.REVVY__Catalog_Node__r.REVVY__LocaleName_F__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>DESCRIPTION</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>REVVY__MnCatalogNode__c</referenceTo>
        <relationshipLabel>Toro Quote Item</relationshipLabel>
        <relationshipName>Toro_Quote_Item</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Toro Quote Item</label>
    <nameField>
        <displayFormat>TQ-{0000000}</displayFormat>
        <label>Toro Quote Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Toro Quote Item</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Toro_QuoteItem_SubLine__c.object
<CustomObject>
    <fields>
        <fullName>Product_Name__c</fullName>
        <formula>Quote_Item_Sub_Line__r.REVVY__Catalog_Node__r.REVVY__LocaleName_F__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>DESCRIPTION</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <referenceTo>REVVY__MnCatalogNode__c</referenceTo>
        <relationshipLabel>Toro Quote Item Sub Lines</relationshipLabel>
        <relationshipName>Toro_Quote_Item_Sub_Lines</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Toro Quote Item Sub Line</label>
    <nameField>
        <displayFormat>TQS-{00000}</displayFormat>
        <label>Toro Quote Item Sub Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Toro Quote Item Sub Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ToroLargePackagePricingProgramHelper.cls
public class ToroLargePackagePricingProgramHelper extends ToroPricingProgram {
	
	public override List<Schema.FieldSetMember> getQuoteFields() {
		system.debug('ToroLargePackagePricingProgramHelper --- getQuoteFields');
		return SObjectType.Revvy__MnQuote__c.FieldSets.REVVY__Quote_Header_Fields.getFields();
	}

	public override List<Schema.FieldSetMember> getToroQuoteItemFields() {
		List<Schema.FieldSetMember> fsl = SObjectType.Toro_QuoteItem__c.FieldSets.Large_Package_Quote_Line_Cols.getFields();
		return fsl;
	}
	public override List<Schema.FieldSetMember> getToroQuoteItemUpdatableFields() {
		return SObjectType.Toro_QuoteItem__c.FieldSets.Large_Package_Quote_Line_Updatable_Cols.getFields();
	}
	public override List<Schema.FieldSetMember> getToroQuoteItemSublineFields() {
		List<Schema.FieldSetMember> fsl = SObjectType.Toro_QuoteItem_SubLine__c.FieldSets.Large_Package_Price_Program_Quote_SubLin.getFields();
		return fsl;
	}
	public override List<Schema.FieldSetMember> getToroQuoteItemSublineUpdatableFields() {
		return SObjectType.Toro_QuoteItem_SubLine__c.FieldSets.Large_Package_Quote_SubLine_Updatable_Co.getFields();
	}
	public override List<Schema.FieldSetMember> getToroQuoteItemSummaryFields() {
		return SObjectType.Toro_QuoteItem__c.FieldSets.Price_Program_Quote_Summary.getFields();
	}

	public override List<ToroSelectOption> retrievePricingMethodOptions() {
		List<ToroSelectOption> ret = new List<ToroSelectOption>();
		if (Schema.sObjectType.REVVY__MnPriceListLine__c.fields.REVVY__SuggestedPrice__c.isAccessible()) {
			ret.add(new ToroSelectOption('% of DNET','% of DNET'));	
		}
		ret.add(new ToroSelectOption('% off MSRP','% off MSRP'));
		ret.add(new ToroSelectOption('Total Award $','Total Award $'));
		ret.add(new ToroSelectOption('Gross Profit %','Gross Profit %'));
		return ret;
	}
	
	public override List<ToroSelectOption> retrieveDemoPricingProgramOptions() {
		List<ToroSelectOption> sels = new List<ToroSelectOption>();
		for(Toro_PricingProgram__c pp : [SELECT Name, PricingProgramStyle__c, ExternalId__c FROM Toro_PricingProgram__c 
									where PricingProgramStyle__c = 'Demo' AND Exclude__c = false order by externalID__c asc]){
			sels.add(new ToroSelectOption(pp.ExternalId__c+ ';' + pp.PricingProgramStyle__c, pp.name));
		}
		return sels;
	}
	public override boolean displayPerformancePart() {
		return true;
	}


	public decimal lookupRebateAsPercentOfDNet(decimal percentOfDNet, List<Toro_PricingProgramLine__c> dNetLineList ) {
		decimal result = 0;
		decimal x3 = percentOfDNet;

		//system.debug('lookupRebateAsPercentOfDNet---x3='+ x3);
		for(integer i =dNetLineList.size()-1; i > 0  ; i--) {
			Toro_PricingProgramLine__c l = dNetLineList[i];
			//system.debug('lookupRebateAsPercentOfDNet---high='+ dNetLineList[i].Award_Price_as_a_Percent_of_DN__c + ' low=' +
			//	dNetLineList[i-1].Award_Price_as_a_Percent_of_DN__c);
			if(x3 < dNetLineList[i].Award_Price_as_a_Percent_of_DN__c && x3 > dNetLineList[i-1].Award_Price_as_a_Percent_of_DN__c){
				decimal x1=(dNetLineList[i].Award_Price_as_a_Percent_of_DN__c)/100;
				decimal x2=(dNetLineList[i-1].Award_Price_as_a_Percent_of_DN__c)/100;
				decimal y1=(dNetLineList[i].Rebate_as_a_Percent_of_DN__c)/100;
				decimal y2=(dNetLineList[i-1].Rebate_as_a_Percent_of_DN__c)/100;
				x3 = x3/100;
				result = y2 -(((x3-x2)*(y2-y1)));
				break;
			}
		}
		return result;
	}
	public override List<Toro_QuoteItem__c> calculateRebateMarginImpl(Id quoteId, String priceProgram,
															String priceMethod, List<Toro_QuoteItem__c> quoteItemList ){
		
		return quoteItemList;
	}

	

	/**
	 *
	 * description
	 *
	 * @param  name    description
	 * @return return_type
	 */
	public override List<Toro_QuoteItem__c> postCalculateRebateMargin(Id quoteId
																		, String priceProgram
																		, String priceMethod
																		, List<Toro_QuoteItem__c> quoteItemList
	) {
		final Toro_PricingProgram__c pricingProgram = [SELECT
															OutCrossThreshold__c
															, MinimumThreshold__c
															, MinimumTractionUnits__c
														FROM
															Toro_PricingProgram__c
														WHERE
															Name = :priceProgram LIMIT 1];

		Revvy__MnQuote__c quote = [SELECT
										Toro_ApprovalReason__c
										, Toro_ApprovalRequired__c
										, Total_Extended_DNet__c
									FROM
										Revvy__MnQuote__c
									WHERE
										Id = :quoteId LIMIT 1];

		Boolean containsOutCross = checkForOutCrossProducts(quoteItemList);
		Integer numberOfTractionUnits = getNumberOfTractionUnits(quoteItemList);

		// quotes that contain outcross items have a separate threshold
		if (containsOutCross && quote.Total_Extended_DNet__c < pricingProgram.OutCrossThreshold__c) {
			quote.Toro_ApprovalRequired__c = true;
			quote.Toro_ApprovalReason__c = 'Total Extended DNet must exceed ' + pricingProgram.OutCrossThreshold__c;
		}

		else if (!containsOutcross && quote.Total_Extended_DNet__c < pricingProgram.MinimumThreshold__c) {
			quote.Toro_ApprovalRequired__c = true;
			quote.Toro_ApprovalReason__c = 'Total Extended DNet must exceed ' + pricingProgram.MinimumThreshold__c;
		}

		else if (numberOfTractionUnits < pricingProgram.MinimumTractionUnits__c) {
			quote.Toro_ApprovalRequired__c = true;
			quote.Toro_ApprovalReason__c = 'Quote must contain at least ' + pricingProgram.MinimumTractionUnits__c + ' traction unit(s).' ;
		}

		if (quote.Toro_ApprovalRequired__c) update quote;

		return 	quoteItemList;
	}

	/**
	 *
	 * returns the number of Traction Units in a quote
	 *
	 * @param  quoteItemList    the list of Toro Quote Items
	 * @return count of traction units
	 */
	public Integer getNumberOfTractionUnits(List<Toro_QuoteItem__c> quoteItemList) {
		// toro product type = 'Finished Good' (catalog node field) Toro_Product_Type__c
		Integer count = 0;
		System.debug('\n\nquoteItemList:\n\n' + quoteItemList + '\n\n');
		for (Toro_QuoteItem__c quoteItem : quoteItemList) {
			if (quoteItem.Product__r.Toro_Product_Type__c == 'Finished Good') {
				count++;
			}
		}
		System.debug('\n\n@@count: ' + count + '\n\n');
		return count;
	}

	/**
	 *
	 * check if the quote items contain an Out-Cross unit
	 *
	 * @param  quoteItemList    the list of Toro Quote Items
	 * @return true/false
	 */
	public Boolean checkForOutCrossProducts(List<Toro_QuoteItem__c> quoteItemList) {
		System.debug('\n\n@@checkForOutCrossProducts quoteItemList: ' + quoteItemList + '\n\n');
		for (Toro_QuoteItem__c quoteItem : quoteItemList) {
			if (quoteItem.Product_Name__c.startsWithIgnorecase('OUTCROSS')) {
				System.debug('\n\n@@contains outcross\n\n');
				return true;
			}
		}

		return false;
	}
}