objects/REVVY__MnQuoteItem__c.object
<CustomObject>
    <fields>
        <fullName>QuoteItem_Extension__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>QuoteItem Extension</label>
        <referenceTo>Toro_QuoteItem__c</referenceTo>
        <relationshipLabel>Quote Line Items</relationshipLabel>
        <relationshipName>Quote_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/REVVY__MnStrategy4__c.object
<CustomObject>
    <fields>
        <fullName>External_Id__c</fullName>
        <externalId>true</externalId>
        <label>External_Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

classes/ToroQIExtensionCreatedBatch.cls
global with sharing class ToroQIExtensionCreatedBatch implements Database.Batchable<sObject>, Database.stateful {
	String query;
	List<Id> qiExtensionList {get; set; }
	global ToroQIExtensionCreatedBatch(List<Id> qiExtensions) {
		this.qiExtensionList = qiExtensions;
		query = 'select id, external_Id__c from REVVY__MnStrategy4__c where id in :qiExtensionList';
	}
	global Database.QueryLocator start(Database.BatchableContext BC) {
    	return Database.getQueryLocator(query);
    }  
    global void execute(Database.BatchableContext BC, List<sObject> scope) {
    	
    	List<REVVY__MnQuoteItem__c> qis = new List<REVVY__MnQuoteItem__c>();
    	List<REVVY__MnStrategy4__c> quoteItemList = (List<REVVY__MnStrategy4__c>)scope;
    	for(REVVY__MnStrategy4__c tqi : quoteItemList) {
    		 qis.add(new REVVY__MnQuoteItem__c(Id =tqi.External_Id__c, QuoteItem_Extension__c = tqi.Id));		
    	}
    	update qis;	
    	
    }  
    global void finish(Database.BatchableContext BC) {
    	 
    }
}