objects/REVVY__MnCatalogNode__c.object
<CustomObject>
    <fields>
        <fullName>Toro_Product_Tier__c</fullName>
        <label>Toro Product Tier</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Toro_Product_Type__c</fullName>
        <description>Finished Good: Model or Finished Good information
Non-Stock Material: From SAP: Non-stock material is material that is not held in stock because it is consumed immediately.
Semi-Finished Good: Part</description>
        <label>Toro Product Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Finished Good</fullName>
                </value>
                <value>
                    <fullName>Non-Stock Material</fullName>
                </value>
                <value>
                    <fullName>Semi-Finished Good</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

objects/REVVY__MnQuote__c.object
<CustomObject>
</CustomObject>

objects/REVVY__MnQuoteItem__c.object
<CustomObject>
    <fields>
        <fullName>Traction_Unit__c</fullName>
        <description>Select the traction unit the product is for.</description>
        <inlineHelpText>Select the traction unit the product is for.</inlineHelpText>
        <label>Traction Unit</label>
        <picklist>
            <picklistValues>
                <fullName>GreensPro Rollers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Groundsmaster 1337 Series</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Groundsmaster 300/3280 Series</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Groundsmaster 3500/4300 Series</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Groundsmaster 360 Series</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Groundsmaster 4000/4100 Series</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Groundsmaster 4500/4700 Series</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Groundsmaster 5900/5910 Series</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Groundsmaster 7200/7210 Series</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HoverPro 400/450/550</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MH-400</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Outcross 9060</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pro Force</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ProCore Aerators &amp; Processor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ProPass 200</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ProSweep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Workman Vehicles</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>All other Commercial Wholegoods</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Please Select:</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

classes/ToroNationalAccountPricingProgramHTest.cls
@isTest
private class ToroNationalAccountPricingProgramHTest {
	
	@testSetup static void setupData() {
		ToroTestData.loadTestData();
		ToroTestData.loadQuoteTestData();
		
		Revvy__MnSequenceGen__c sequence = new Revvy__MnSequenceGen__c(Revvy__ObjectName__c='MnQuoteItem__c', REVVY__CurrentValue__c=1);
		insert sequence;
		
		
	}

	@isTest static void test_get_field_methods() {
		List<REVVY__MnCatalogNode__c> products = [select id from REVVY__MnCatalogNode__c];
		String[] tiers = new String[]{'Tier 1', 'Tier 2', 'Parts'};
		String[] productTypes = new String[]{'Finished Good', 'Semi-Finished Good', 'Non-Stock Material'};
		Integer index = 0;
		Integer ptIdx=0;
		for(REVVY__MnCatalogNode__c p: products) {
			p.Toro_Product_Tier__c = tiers[index++];
			index = Math.mod(index, tiers.size());
			p.Toro_Product_Type__c = productTypes[ptIdx++];	
			ptIdx = Math.mod(ptIdx, productTypes.size());
		}
		products[0].Toro_Product_Tier__c='Tier 3';
		update products;
		//Groundsmaster 4500/4700 Series
		List<REVVY__MnQuoteItem__c> quoteItems = [select id from REVVY__MnQuoteItem__c];
		quoteItems[0].Traction_Unit__c='Groundsmaster 4500/4700 Series';
		update quoteItems[0];
		Revvy__MnQuote__c quote = [select Id from Revvy__MnQuote__c limit 1];
		ToroNationalAccountPricingProgramHelper tlpp = new ToroNationalAccountPricingProgramHelper();
		tlpp.performancePartFlag=true;
		system.assert(tlpp.displaySetupFee());
		List<ToroSelectOption> options = tlpp.retrievePricingMethodOptions();
		ToroPricingProgramData ppd = new ToroPricingProgramData('GreenwayGolf;Standard');
		tlpp.initialize(quote.Id);
		
		tlpp.quoteItems = tlpp.calculateRebateMargin(quote.Id, ppd.externalId, '% off MSRP', tlpp.quoteItems, false);
		tlpp.quoteItems = tlpp.calculateRebateMargin(quote.Id, ppd.externalId, '% off MSRP', tlpp.quoteItems, false);
	}
	@isTest static void test_get_field_methods_2() {
		//04109
		List<REVVY__MnCatalogNode__c> products = [select id,REVVY__Id__c from REVVY__MnCatalogNode__c];
		String[] tiers = new String[]{'Tier 1', 'Tier 2', 'Parts'};
		Integer index = 0;
		for(REVVY__MnCatalogNode__c p: products) {
			if(p.REVVY__Id__c != '04109') {
				p.Toro_Product_Tier__c = tiers[index++];
				index = Math.mod(index, tiers.size());	
			} else {
				p.Toro_Product_Tier__c = 'Tier 3';
			}
			
			p.Toro_Product_Type__c = 'Semi-Finished Good';	
		}
		
		update products;
		//Groundsmaster 4500/4700 Series
		List<REVVY__MnQuoteItem__c> quoteItems = [select id from REVVY__MnQuoteItem__c];
		quoteItems[0].Traction_Unit__c='Groundsmaster 4500/4700 Series';
		update quoteItems[0];
		
		Revvy__MnQuote__c quote = [select Id from Revvy__MnQuote__c limit 1];
		ToroNationalAccountPricingProgramHelper tlpp = new ToroNationalAccountPricingProgramHelper();
		tlpp.performancePartFlag=true;
		system.assert(tlpp.displaySetupFee());
		List<ToroSelectOption> options = tlpp.retrievePricingMethodOptions();
		ToroPricingProgramData ppd = new ToroPricingProgramData('GreenwayGolf;Standard');
		tlpp.initialize(quote.Id);
		
		tlpp.quoteItems = tlpp.calculateRebateMargin(quote.Id, ppd.externalId, '% off MSRP', tlpp.quoteItems, false);
		tlpp.quoteItems = tlpp.calculateRebateMargin(quote.Id, ppd.externalId, '% off MSRP', tlpp.quoteItems, false);
	}
	@isTest static void test_method_two() {
		ToroNationalAccountPricingProgramHelper tlpp = new ToroNationalAccountPricingProgramHelper();
		tlpp.displayPerformancePart();
		System.assert(tlpp.getQuoteFields() != null);
		System.assert(tlpp.getToroQuoteItemFields() != null);
		System.assert(tlpp.getToroQuoteItemUpdatableFields() != null);
		System.assert(tlpp.getToroQuoteItemSublineFields() != null);
		tlpp.getToroQuoteItemSublineUpdatableFields();
		System.assert(tlpp.getToroQuoteItemSummaryFields() != null);
		tlpp.retrieveDemoPricingProgramOptions();
	}
	
}