objects/Toro_PricingProgramHelperFactory__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Pricing Program Factory</description>
    <fields>
        <fullName>ClassName__c</fullName>
        <label>Class Name</label>
        <length>127</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PricingProgramName__c</fullName>
        <label>Pricing Program Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Pricing Program Helper</label>
</CustomObject>

classes/ToroPricingProgramHelperCache.cls
public with sharing class ToroPricingProgramHelperCache implements Cache.CacheBuilder {
	public Object doLoad(String pricingProgramHelper) {
        //Cache.OrgPartition orgPart = Cache.Org.getPartition(constPartitionName);
		List<Toro_PricingProgramHelperFactory__c> pricingProgramSettings = Toro_PricingProgramHelperFactory__c.getAll().values();
		Map<String, ToroPricingProgram> pricingProgramHelperMap = new Map<String, ToroPricingProgram>();
		for(Toro_PricingProgramHelperFactory__c pp : pricingProgramSettings) {
			system.debug(pp);
			ToroPricingProgram tpp = ToroPriceProgramFactory.newPricingProgramInstance(pp.ClassName__c);
			pricingProgramHelperMap.put(pp.PricingProgramName__c, tpp);								
		} 
		pricingProgramHelperMap.put('defaultPricingProgram', new ToroDefaultPricingProgramHelper());				
		return pricingProgramHelperMap;
    }    
    
}